### ISSUE TITLE
Intellicode Throwing System.IO.InvalidDataException [Python]

### ISSUE THREAD

**Issue by adilcpm** [MicrosoftDocs/intellicode#188]
**Product and Version** [VS/VSCode]:
**OS Version** [ArchLinux]:
**IntelliCode Extension Version**: 1.2.6
**Target Platform or Language** [Python]:
**Python Version** : 3.8.2 
**Microsoft Python Language Server** : 0.5.45.0

**Scenario**
Enabling the IntelliCode extension and invoking it on any python file, causes this error ( I can't possibly use it)
Its Raises an System.IO.InvalidDataException: End of Central Directory record could not be found

Python Language Server [Output in VSCode]
```
[Info  - 10:25:56 pm] Analysis cache path: /home/adil/.cache/Microsoft/Python Language Server
[Info  - 10:25:56 pm] Microsoft Python Language Server version 0.5.45.0
[Info  - 10:25:56 pm] Workspace root: /home/adil/microblog
[Info  - 10:25:57 pm] GetCurrentSearchPaths /home/adil/microblog/venv/bin/python3 
[Info  - 10:25:57 pm] Interpreter search paths:
[Info  - 10:25:57 pm]     /usr/lib/python3.8
[Info  - 10:25:57 pm]     /usr/lib/python3.8/lib-dynload
[Info  - 10:25:57 pm]     /home/adil/microblog/venv/lib/python3.8/site-packages
[Info  - 10:25:57 pm] User search paths:
[Info  - 10:25:57 pm] Initializing for /home/adil/microblog/venv/bin/python3
[Info  - 10:25:57 pm] Analysis caching mode: None.
[Error - 10:26:32 pm] Exception in IntelliCode extension for Microsoft Python Language Server: System.IO.InvalidDataException: End of Central Directory record could not be found.
   at System.IO.Compression.ZipArchive.ReadEndOfCentralDirectory()
   at System.IO.Compression.ZipArchive.Init(Stream stream, ZipArchiveMode mode, Boolean leaveOpen)
   at System.IO.Compression.ZipArchive..ctor(Stream stream, ZipArchiveMode mode, Boolean leaveOpen, Encoding entryNameEncoding)
   at System.IO.Compression.ZipFile.Open(String archiveFileName, ZipArchiveMode mode, Encoding entryNameEncoding)
   at System.IO.Compression.ZipFile.ExtractToDirectory(String sourceArchiveFileName, String destinationDirectoryName, Encoding entryNameEncoding, Boolean overwriteFiles)
   at System.IO.Compression.ZipFile.ExtractToDirectory(String sourceArchiveFileName, String destinationDirectoryName, Boolean overwriteFiles)
   at Microsoft.PythonTools.Analysis.Pythia.PythiaModelLoader.LoadModel(String modelPath, ILogger logger, IDictionary`2& tokenIdMap, IList`1& tokens, InferenceSession& session, PythiaModelMetaData& modelMetaData)
   at Microsoft.PythonTools.Analysis.Pythia.PythiaService.<LoadModel>b__18_0()
   at System.Threading.Tasks.Task.InnerInvoke()
   at System.Threading.Tasks.Task.<>c.<.cctor>b__274_0(Object obj)
   at System.Threading.ExecutionContext.RunFromThreadPoolDispatchLoop(Thread threadPoolThread, ExecutionContext executionContext, ContextCallback callback, Object state)
--- End of stack trace from previous location where exception was thrown ---
   at System.Threading.ExecutionContext.RunFromThreadPoolDispatchLoop(Thread threadPoolThread, ExecutionContext executionContext, ContextCallback callback, Object state)
   at System.Threading.Tasks.Task.ExecuteWithThreadLocal(Task& currentTaskSlot, Thread threadPoolThread)
--- End of stack trace from previous location where exception was thrown ---
   at Microsoft.PythonTools.Analysis.Pythia.PythiaService.GetRecommendationsAsync(IDocumentAnalysis analysis, CompletionList completionList, SourceLocation location, Int32 recommendataionLimit, CancellationToken cancellationToken)
   at Microsoft.PythonTools.Analysis.Pythia.LanguageServerExtension.HandleCompletionAsync(IDocumentAnalysis analysis, SourceLocation location, CompletionList completionList, CancellationToken token)
[Error - 10:26:32 pm] For more information about IntelliCode deep learning model, see https://aka.ms/intellicode/vscode-experiments
```

**Comment by ayim** [comment]
@[adilcpm](https://github.com/adilcpm) if you're continuing to see issues, we'd love to hear from you.
Please give us a shout in a new issue!
