### ISSUE TITLE
Sorry, something went wrong activating IntelliCode support for Python.

### ISSUE THREAD

**Issue by Abdelrahman-shrif** [MicrosoftDocs/intellicode#229]
Python Output :
User belongs to experiment group 'ShowPlayIcon - start'
User belongs to experiment group 'DebugAdapterFactory - experiment'
User belongs to experiment group 'PtvsdWheels37 - experiment'
User belongs to experiment group 'UseTerminalToGetActivatedEnvVars - control'
User belongs to experiment group 'AA_testing - control'
User belongs to experiment group 'LocalZMQKernel - experiment'
User belongs to experiment group 'CollectLSRequestTiming - control'
User belongs to experiment group 'CollectNodeLSRequestTiming - experiment'
User belongs to experiment group 'EnableIPyWidgets - experiment'
User belongs to experiment group 'RunByLine - experiment'
User belongs to experiment group 'CustomEditorSupport - control'
User belongs to experiment group 'pythonaacf'
Error 2020-09-24 05:57:38: Exception while attempting zmq : [Error: The specified module could not be found.
\\?\c:\Users\Ghorab\.vscode\extensions\ms-python.python-2020.9.111407\out\client\node_modules\zeromq\prebuilds\win32-ia32\electron.napi.node
	at process.func [as dlopen] (electron/js2c/asar.js:140:31)
	at Object.Module._extensions..node (internal/modules/cjs/loader.js:1081:18)
	at Object.func [as .node] (electron/js2c/asar.js:140:31)
	at Module.load (internal/modules/cjs/loader.js:862:32)
	at Module._load (internal/modules/cjs/loader.js:774:14)
	at Function.Module._load (electron/js2c/asar.js:769:28)
	at Function.t._load (c:\Users\Ghorab\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:1046:268)
	at Function.i._load (c:\Users\Ghorab\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:1015:981)
	at Function.n._load (c:\Users\Ghorab\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:1012:303)
	at Module.require (internal/modules/cjs/loader.js:899:19)
	at n (c:\Users\Ghorab\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\loader.js:16:135)
	at load (c:\Users\Ghorab\.vscode\extensions\ms-python.python-2020.9.111407\out\client\node_modules\node-gyp-build\index.js:21:10)
	at Object.<anonymous> (c:\Users\Ghorab\.vscode\extensions\ms-python.python-2020.9.111407\out\client\node_modules\zeromq\lib\native.js:6:43)
	at Module.o._compile (c:\Users\Ghorab\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\loader.js:16:360)
	at Object.Module._extensions..js (internal/modules/cjs/loader.js:1051:10)
	at Module.load (internal/modules/cjs/loader.js:862:32)
	at Module._load (internal/modules/cjs/loader.js:774:14)
	at Function.Module._load (electron/js2c/asar.js:769:28)
	at Function.t._load (c:\Users\Ghorab\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:1046:268)
	at Function.i._load (c:\Users\Ghorab\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:1015:981)
	at Function.n._load (c:\Users\Ghorab\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:1012:303)
	at Module.require (internal/modules/cjs/loader.js:899:19)
	at n (c:\Users\Ghorab\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\loader.js:16:135)
	at Object.<anonymous> (c:\Users\Ghorab\.vscode\extensions\ms-python.python-2020.9.111407\out\client\node_modules\zeromq\lib\index.js:3:16)
	at Module.o._compile (c:\Users\Ghorab\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\loader.js:16:360)
	at Object.Module._extensions..js (internal/modules/cjs/loader.js:1051:10)
	at Module.load (internal/modules/cjs/loader.js:862:32)
	at Module._load (internal/modules/cjs/loader.js:774:14)
	at Function.Module._load (electron/js2c/asar.js:769:28)
	at Function.t._load (c:\Users\Ghorab\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:1046:268)
	at Function.i._load (c:\Users\Ghorab\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:1015:981)
	at Function.n._load (c:\Users\Ghorab\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:1012:303)
	at Module.require (internal/modules/cjs/loader.js:899:19)
	at n (c:\Users\Ghorab\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\loader.js:16:135)
	at Object.<anonymous> (c:\Users\Ghorab\.vscode\extensions\ms-python.python-2020.9.111407\out\client\extension.js:24:302770)
	at n (c:\Users\Ghorab\.vscode\extensions\ms-python.python-2020.9.111407\out\client\extension.js:1:186)
	at c:\Users\Ghorab\.vscode\extensions\ms-python.python-2020.9.111407\out\client\extension.js:56:730603
	at processTicksAndRejections (internal/process/task_queues.js:94:5)
	at async d.zmqSupportedImpl (c:\Users\Ghorab\.vscode\extensions\ms-python.python-2020.9.111407\out\client\extension.js:56:730570)]
> conda --version
> pyenv root
> python3.7 c:\Users\Ghorab\.vscode\extensions\ms-python.python-2020.9.111407\pythonFiles\pyvsc-run-isolated.py -c "import sys;print(sys.executable)"
> python3.6 c:\Users\Ghorab\.vscode\extensions\ms-python.python-2020.9.111407\pythonFiles\pyvsc-run-isolated.py -c "import sys;print(sys.executable)"
> python3 c:\Users\Ghorab\.vscode\extensions\ms-python.python-2020.9.111407\pythonFiles\pyvsc-run-isolated.py -c "import sys;print(sys.executable)"
> python2 c:\Users\Ghorab\.vscode\extensions\ms-python.python-2020.9.111407\pythonFiles\pyvsc-run-isolated.py -c "import sys;print(sys.executable)"
> python c:\Users\Ghorab\.vscode\extensions\ms-python.python-2020.9.111407\pythonFiles\pyvsc-run-isolated.py -c "import sys;print(sys.executable)"
> py -3.7 c:\Users\Ghorab\.vscode\extensions\ms-python.python-2020.9.111407\pythonFiles\pyvsc-run-isolated.py -c "import sys;print(sys.executable)"
> py -3.6 c:\Users\Ghorab\.vscode\extensions\ms-python.python-2020.9.111407\pythonFiles\pyvsc-run-isolated.py -c "import sys;print(sys.executable)"
> py -3 c:\Users\Ghorab\.vscode\extensions\ms-python.python-2020.9.111407\pythonFiles\pyvsc-run-isolated.py -c "import sys;print(sys.executable)"
> ~\AppData\Local\Programs\Python\Python38\python.exe c:\Users\Ghorab\.vscode\extensions\ms-python.python-2020.9.111407\pythonFiles\pyvsc-run-isolated.py -c "import sys;print(sys.executable)"
> py -2 c:\Users\Ghorab\.vscode\extensions\ms-python.python-2020.9.111407\pythonFiles\pyvsc-run-isolated.py -c "import sys;print(sys.executable)"
> conda info --json
Error 2020-09-24 05:58:56: Failed to check if file needs to be fixed [EntryNotFound (FileSystemError): Unable to read file 'h:\Abd El Rahman\programming\tasks\.vscode\settings.json' (EntryNotFound (FileSystemError): Error: ENOENT: no such file or directory, open 'h:\Abd El Rahman\programming\tasks\.vscode\settings.json')
	at _handleError (c:\Users\Ghorab\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:706:74)
	at processTicksAndRejections (internal/process/task_queues.js:94:5)
	at async y.readText (c:\Users\Ghorab\.vscode\extensions\ms-python.python-2020.9.111407\out\client\extension.js:1:498595)
	at async p.doesFileNeedToBeFixed (c:\Users\Ghorab\.vscode\extensions\ms-python.python-2020.9.111407\out\client\extension.js:56:960982)
	at async c:\Users\Ghorab\.vscode\extensions\ms-python.python-2020.9.111407\out\client\extension.js:56:960109
	at async Promise.all (index 1)
	at async p.getFilesToBeFixed (c:\Users\Ghorab\.vscode\extensions\ms-python.python-2020.9.111407\out\client\extension.js:56:960055)
	at async p.updateTestSettings (c:\Users\Ghorab\.vscode\extensions\ms-python.python-2020.9.111407\out\client\extension.js:56:959682)] {
  code: 'FileNotFound',
  name: 'EntryNotFound (FileSystemError)'
}
Python interpreter path: ~\AppData\Local\Programs\Python\Python38\python.exe
Starting Microsoft Python language server.
Error 2020-09-24 05:59:14: Detection of Python Interpreter for Command python3 and args  failed as file  does not exist
Error 2020-09-24 05:59:14: Failed to get interpreter information for 'C:\Users\Ghorab\AppData\Local\Microsoft\WindowsApps\python3.exe' [Error: Command failed: "C:\\Users\Ghorab\AppData\Local\Microsoft\WindowsApps\python3.exe" "c:\Users\Ghorab\.vscode\extensions\ms-python.python-2020.9.111407\pythonFiles\pyvsc-run-isolated.py" "c:\Users\Ghorab\.vscode\extensions\ms-python.python-2020.9.111407\pythonFiles\interpreterInfo.py"

	at ChildProcess.exithandler (child_process.js:304:12)
	at ChildProcess.emit (events.js:223:5)
	at maybeClose (internal/child_process.js:1021:16)
	at Socket.<anonymous> (internal/child_process.js:430:11)
	at Socket.emit (events.js:223:5)
	at Pipe.<anonymous> (net.js:664:12)] {
  killed: true,
  code: null,
  signal: 'SIGTERM',
  cmd: '"C:\\\\Users\\Ghorab\\AppData\\Local\\Microsoft\\WindowsApps\\python3.exe" "c:\\Users\\Ghorab\\.vscode\\extensions\\ms-python.python-2020.9.111407\\pythonFiles\\pyvsc-run-isolated.py" "c:\\Users\\Ghorab\\.vscode\\extensions\\ms-python.python-2020.9.111407\\pythonFiles\\interpreterInfo.py"'
}
Error 2020-09-24 05:59:14: Failed to get interpreter information for 'C:\Users\Ghorab\AppData\Local\Microsoft\WindowsApps\python.exe' [Error: Command failed: "C:\\Users\Ghorab\AppData\Local\Microsoft\WindowsApps\python.exe" "c:\Users\Ghorab\.vscode\extensions\ms-python.python-2020.9.111407\pythonFiles\pyvsc-run-isolated.py" "c:\Users\Ghorab\.vscode\extensions\ms-python.python-2020.9.111407\pythonFiles\interpreterInfo.py"

	at ChildProcess.exithandler (child_process.js:304:12)
	at ChildProcess.emit (events.js:223:5)
	at maybeClose (internal/child_process.js:1021:16)
	at Socket.<anonymous> (internal/child_process.js:430:11)
	at Socket.emit (events.js:223:5)
	at Pipe.<anonymous> (net.js:664:12)] {
  killed: true,
  code: null,
  signal: 'SIGTERM',
  cmd: '"C:\\\\Users\\Ghorab\\AppData\\Local\\Microsoft\\WindowsApps\\python.exe" "c:\\Users\\Ghorab\\.vscode\\extensions\\ms-python.python-2020.9.111407\\pythonFiles\\pyvsc-run-isolated.py" "c:\\Users\\Ghorab\\.vscode\\extensions\\ms-python.python-2020.9.111407\\pythonFiles\\interpreterInfo.py"'
}
Error 2020-09-24 05:59:16: Detection of Python Interpreter for Command py and args -3.6 failed as file Python 3.6 not found!

 -3.8-64
 -3.8-32 does not exist
Error 2020-09-24 05:59:16: Detection of Python Interpreter for Command py and args -3.7 failed as file Python 3.7 not found!

 -3.8-64
 -3.8-32 does not exist
Error 2020-09-24 05:59:18: Detection of Python Interpreter for Command py and args -2 failed as file Python 2 not found!

 -3.8-64
 -3.8-32 does not exist
> ~\AppData\Local\Programs\Python\Python38\python.exe c:\Users\Ghorab\.vscode\extensions\ms-python.python-2020.9.111407\pythonFiles\pyvsc-run-isolated.py -c "import jupyter"
> ~\AppData\Local\Programs\Python\Python38\python.exe c:\Users\Ghorab\.vscode\extensions\ms-python.python-2020.9.111407\pythonFiles\pyvsc-run-isolated.py -c "import jupyter"
> ~\AppData\Local\Programs\Python\Python38\python.exe c:\Users\Ghorab\.vscode\extensions\ms-python.python-2020.9.111407\pythonFiles\pyvsc-run-isolated.py -c "import notebook"
> ~\AppData\Local\Programs\Python\Python38\python.exe c:\Users\Ghorab\.vscode\extensions\ms-python.python-2020.9.111407\pythonFiles\pyvsc-run-isolated.py -c "import notebook"
> ~\AppData\Local\Programs\Python\Python38\python.exe c:\Users\Ghorab\.vscode\extensions\ms-python.python-2020.9.111407\pythonFiles\pyvsc-run-isolated.py -c "import jupyter"
> ~\AppData\Local\Programs\Python\Python38\python.exe c:\Users\Ghorab\.vscode\extensions\ms-python.python-2020.9.111407\pythonFiles\pyvsc-run-isolated.py -c "import jupyter"
> ~\AppData\Local\Programs\Python\Python38\python.exe c:\Users\Ghorab\.vscode\extensions\ms-python.python-2020.9.111407\pythonFiles\pyvsc-run-isolated.py -c "import notebook"
> ~\AppData\Local\Programs\Python\Python38\python.exe c:\Users\Ghorab\.vscode\extensions\ms-python.python-2020.9.111407\pythonFiles\pyvsc-run-isolated.py -c "import notebook"
Error 2020-09-24 05:59:21: Error starting server in serverPreload:  [i [Error]: Jupyter cannot be started. Error attempting to locate jupyter: Data Science libraries jupyter and notebook are not installed in interpreter Python 3.8.5 64-bit.
	at b.startServer (c:\Users\Ghorab\.vscode\extensions\ms-python.python-2020.9.111407\out\client\extension.js:56:315173)
	at processTicksAndRejections (internal/process/task_queues.js:94:5)
	at async b.createServer (c:\Users\Ghorab\.vscode\extensions\ms-python.python-2020.9.111407\out\client\extension.js:56:314615)
	at async connect (c:\Users\Ghorab\.vscode\extensions\ms-python.python-2020.9.111407\out\client\extension.js:56:442228)
	at async l.createServerIfNecessary (c:\Users\Ghorab\.vscode\extensions\ms-python.python-2020.9.111407\out\client\extension.js:56:519327)] {
  action: 'https://aka.ms/pyaiinstall',
  actionTitle: 'Get more help'
}
Error 2020-09-24 05:59:39: Listing Nuget Packages, Class name = d, completed in 23553ms, has a falsy return value, Arg 1: "https://pvsc.blob.core.windows.net", Arg 2: "python-language-server-stable", Arg 3: "Python-Language-Server-win-x64", Arg 4: "https://pvsc.azureedge.net", Arg 5: <Uri:h:\Abd El Rahman\programming\tasks\Little Project\Expramint.py>, Return Value: undefined [Error: read ECONNRESET
	at TLSWrap.onStreamRead (internal/stream_base_commons.js:200:27)] {
  errno: 'ECONNRESET',
  code: 'ECONNRESET',
  syscall: 'read'
}
Error 2020-09-24 05:59:39: Get latest language server nuget package version, Class name = d, completed in 23603ms, has a falsy return value, Arg 1: <Uri:h:\Abd El Rahman\programming\tasks\Little Project\Expramint.py>, Arg 2: "0.5.30", Return Value: undefined [Error: read ECONNRESET
	at TLSWrap.onStreamRead (internal/stream_base_commons.js:200:27)] {
  errno: 'ECONNRESET',
  code: 'ECONNRESET',
  syscall: 'read'
}
Error 2020-09-24 05:59:39: Get latest version of language server, Class name = f, completed in 23603ms, has a falsy return value, Arg 1: <Uri:h:\Abd El Rahman\programming\tasks\Little Project\Expramint.py>, Return Value: undefined [Error: read ECONNRESET
	at TLSWrap.onStreamRead (internal/stream_base_commons.js:200:27)] {
  errno: 'ECONNRESET',
  code: 'ECONNRESET',
  syscall: 'read'
}
Error 2020-09-24 05:59:40: Get language server folder name, Class name = f, completed in 25401ms, has a falsy return value, Arg 1: <Uri:h:\Abd El Rahman\programming\tasks\Little Project\Expramint.py>, Return Value: undefined [TypeError: Cannot read property 'version' of undefined
	at u.getLanguageServerFolderName (c:\Users\Ghorab\.vscode\extensions\ms-python.python-2020.9.111407\out\client\extension.js:24:193095)
	at processTicksAndRejections (internal/process/task_queues.js:94:5)]
Error 2020-09-24 05:59:40: Failed to activate language server, Class name = a, completed in 25416ms, has a falsy return value, Arg 1: <Uri:h:\Abd El Rahman\programming\tasks\Little Project\Expramint.py>, Arg 2: {"architecture":3,"path":"C:\\Users\\Ghorab\\AppData\\Local\\Programs\\Python\\Python38\\python.exe","version":{"options":{"loose":false,"includePrerelease":false},"loose":false,"raw":"3.8.5-final","major":3,"minor":8,"patch":5,"prerelease":["final"],"build":[],"version":"3.8.5-final"},"sysPrefix":"C:\\Users\\Ghorab\\AppData\\Local\\Programs\\Python\\Python38","fileHash":"3c34657a756a0cf9aac212845248495355139976e265907903c6ef3707f946fc73d08b265b235e24e6a581a0a5d4de11247733040bfcdfef1a89ed33b0da257f","companyDisplayName":"Python Software Foundation","envType":"Unknown","displayName":"Python 3.8.5 64-bit"}, Return Value: undefined [TypeError: Cannot read property 'version' of undefined
	at u.getLanguageServerFolderName (c:\Users\Ghorab\.vscode\extensions\ms-python.python-2020.9.111407\out\client\extension.js:24:193095)
	at processTicksAndRejections (internal/process/task_queues.js:94:5)]
We encountered an issue starting the language server. Reverting to Jedi language engine. Check the Python output panel for details.
Error 2020-09-24 05:59:40: Failed to activate a workspace, Class name = y, completed in 123037ms, has a falsy return value, Arg 1: <Uri:h:\Abd El Rahman\programming\tasks\Little Project\Expramint.py>, Return Value: undefined [Error: No matching bindings found for serviceIdentifier: Symbol(ILanguageServerActivator)
 Symbol(ILanguageServerActivator) - named: Jedi 

	at c:\Users\Ghorab\.vscode\extensions\ms-python.python-2020.9.111407\out\client\extension.js:47:258487
	at m (c:\Users\Ghorab\.vscode\extensions\ms-python.python-2020.9.111407\out\client\extension.js:47:258784)
	at e (c:\Users\Ghorab\.vscode\extensions\ms-python.python-2020.9.111407\out\client\extension.js:47:259275)
	at Object.t.plan (c:\Users\Ghorab\.vscode\extensions\ms-python.python-2020.9.111407\out\client\extension.js:47:259938)
	at c:\Users\Ghorab\.vscode\extensions\ms-python.python-2020.9.111407\out\client\extension.js:47:256591
	at e._get (c:\Users\Ghorab\.vscode\extensions\ms-python.python-2020.9.111407\out\client\extension.js:47:256500)
	at e.getTagged (c:\Users\Ghorab\.vscode\extensions\ms-python.python-2020.9.111407\out\client\extension.js:47:255302)
	at e.getNamed (c:\Users\Ghorab\.vscode\extensions\ms-python.python-2020.9.111407\out\client\extension.js:47:255394)
	at a.get (c:\Users\Ghorab\.vscode\extensions\ms-python.python-2020.9.111407\out\client\extension.js:56:1063072)
	at C.createRefCountedServer (c:\Users\Ghorab\.vscode\extensions\ms-python.python-2020.9.111407\out\client\extension.js:47:304090)
	at processTicksAndRejections (internal/process/task_queues.js:94:5)
	at async C.activate (c:\Users\Ghorab\.vscode\extensions\ms-python.python-2020.9.111407\out\client\extension.js:47:301732)
	at async Promise.all (index 4)
	at async y.activateWorkspace (c:\Users\Ghorab\.vscode\extensions\ms-python.python-2020.9.111407\out\client\extension.js:47:296814)]
Error 2020-09-24 05:59:40: Failure during activation. [Error: No matching bindings found for serviceIdentifier: Symbol(ILanguageServerActivator)
 Symbol(ILanguageServerActivator) - named: Jedi 

	at c:\Users\Ghorab\.vscode\extensions\ms-python.python-2020.9.111407\out\client\extension.js:47:258487
	at m (c:\Users\Ghorab\.vscode\extensions\ms-python.python-2020.9.111407\out\client\extension.js:47:258784)
	at e (c:\Users\Ghorab\.vscode\extensions\ms-python.python-2020.9.111407\out\client\extension.js:47:259275)
	at Object.t.plan (c:\Users\Ghorab\.vscode\extensions\ms-python.python-2020.9.111407\out\client\extension.js:47:259938)
	at c:\Users\Ghorab\.vscode\extensions\ms-python.python-2020.9.111407\out\client\extension.js:47:256591
	at e._get (c:\Users\Ghorab\.vscode\extensions\ms-python.python-2020.9.111407\out\client\extension.js:47:256500)
	at e.getTagged (c:\Users\Ghorab\.vscode\extensions\ms-python.python-2020.9.111407\out\client\extension.js:47:255302)
	at e.getNamed (c:\Users\Ghorab\.vscode\extensions\ms-python.python-2020.9.111407\out\client\extension.js:47:255394)
	at a.get (c:\Users\Ghorab\.vscode\extensions\ms-python.python-2020.9.111407\out\client\extension.js:56:1063072)
	at C.createRefCountedServer (c:\Users\Ghorab\.vscode\extensions\ms-python.python-2020.9.111407\out\client\extension.js:47:304090)
	at processTicksAndRejections (internal/process/task_queues.js:94:5)
	at async C.activate (c:\Users\Ghorab\.vscode\extensions\ms-python.python-2020.9.111407\out\client\extension.js:47:301732)
	at async Promise.all (index 4)
	at async y.activateWorkspace (c:\Users\Ghorab\.vscode\extensions\ms-python.python-2020.9.111407\out\client\extension.js:47:296814)]
Error 2020-09-24 05:59:40: sendStartupTelemetry() failed. [Error: No matching bindings found for serviceIdentifier: Symbol(ILanguageServerActivator)
 Symbol(ILanguageServerActivator) - named: Jedi 

	at c:\Users\Ghorab\.vscode\extensions\ms-python.python-2020.9.111407\out\client\extension.js:47:258487
	at m (c:\Users\Ghorab\.vscode\extensions\ms-python.python-2020.9.111407\out\client\extension.js:47:258784)
	at e (c:\Users\Ghorab\.vscode\extensions\ms-python.python-2020.9.111407\out\client\extension.js:47:259275)
	at Object.t.plan (c:\Users\Ghorab\.vscode\extensions\ms-python.python-2020.9.111407\out\client\extension.js:47:259938)
	at c:\Users\Ghorab\.vscode\extensions\ms-python.python-2020.9.111407\out\client\extension.js:47:256591
	at e._get (c:\Users\Ghorab\.vscode\extensions\ms-python.python-2020.9.111407\out\client\extension.js:47:256500)
	at e.getTagged (c:\Users\Ghorab\.vscode\extensions\ms-python.python-2020.9.111407\out\client\extension.js:47:255302)
	at e.getNamed (c:\Users\Ghorab\.vscode\extensions\ms-python.python-2020.9.111407\out\client\extension.js:47:255394)
	at a.get (c:\Users\Ghorab\.vscode\extensions\ms-python.python-2020.9.111407\out\client\extension.js:56:1063072)
	at C.createRefCountedServer (c:\Users\Ghorab\.vscode\extensions\ms-python.python-2020.9.111407\out\client\extension.js:47:304090)
	at processTicksAndRejections (internal/process/task_queues.js:94:5)
	at async C.activate (c:\Users\Ghorab\.vscode\extensions\ms-python.python-2020.9.111407\out\client\extension.js:47:301732)
	at async Promise.all (index 4)
	at async y.activateWorkspace (c:\Users\Ghorab\.vscode\extensions\ms-python.python-2020.9.111407\out\client\extension.js:47:296814)]

VS IntelliCode

**Comment by MikhailArkhipov** [comment]
From the log it appears that download shares are unreachable. 

Looks like some sort of network connection problem. User tries MPLS v1 (not Pylance). Extension goes to download latest. After 25 seconds download fails

**Error 2020-09-24 05:59:39: Get latest language server nuget package version**, Class name = d, completed in 23603ms, has a falsy return value, Arg 1: <Uri:h:\Abd El Rahman\programming\tasks\Little Project\Expramint.py>, Arg 2: "0.5.30", Return Value: u**ndefined [Error: read ECONNRESET**

Could you check if https://pvsc.blob.core.windows.net is reachable.

**Comment by Abdelrahman-shrif** [comment]
Thank You it was helpful I just reload the page in vs and seem that vs redownload Microsoft python language server . 
It happen many times I don't know why but once I reload the page it back to work.
Thank You.

**Comment by markw-t** [comment]
Thanks for letting us know @Abdelrahman-shrif ! I'm closing this issue based on your comment to @MikhailArkhipov above.
