### ISSUE TITLE
VS Intllicode is not working

### ISSUE THREAD

**Issue by vishalverma116** [MicrosoftDocs/intellicode#262]
Issue Type: <b>Performance Issue</b>

It stopped working since last 4 to 5 days. It occurs on startup. I don't know what the hell i going on. All options are enabled still it dosn't work.

Extension version: 1.2.10
VS Code version: Code 1.49.3 (2af051012b66169dde0c4dfae3f5ef48f787ff69, 2020-10-02T17:57:01.595Z)
OS version: Windows_NT x64 10.0.19042

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|AMD A6-7310 APU with AMD Radeon R4 Graphics     (4 x 1996)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>opengl: enabled_on<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|3.47GB (0.57GB free)|
|Process Argv|--crash-reporter-id e8c55eef-f651-4387-9450-63caf6bf5b8c|
|Screen Reader|no|
|VM|0%|
</details><details>
<summary>Process Info</summary>

```
CPU %	Mem MB	   PID	Process
    2	    66	 16972	code main
    0	     7	  1564	   crashpad-handler
    5	   189	  5076	   window (python_codes.py - codes - Visual Studio Code)
    0	   180	   844	     extensionHost
    0	    66	  6568	       electron_node server.js 
    0	     6	  1980	     console-window-host (Windows internal process)
    0	    14	  4012	     watcherService 
    0	    11	 10416	       console-window-host (Windows internal process)
    0	    70	  8808	     searchService
    0	     4	 17080	     C:\WINDOWS\System32\cmd.exe
    3	    92	  8532	   gpu-process
    0	    22	 12228	   utility
    0	    52	 12292	   shared-process
    3	    82	 12784	   window (Issue Reporter)
```

</details>
<details>
<summary>Workspace Info</summary>

```
|  Window (python_codes.py - codes - Visual Studio Code)
|    Folder (codes): 66 files
|      File types: cpp(28) exe(24) json(2) py(2) java(1)
|      Conf files: settings.json(2);
```

</details>

**Comment by catycaldwell** [comment]
@savannahostrowski @jakebailey - adding so you can take a look?

**Comment by jakebailey** [comment]
I don't think there's enough info here to indicate that this is related to Python or Pylance. I think @vishalverma116 may need to provide a bit more info about what they're doing, what message they're seeing, etc, especially given that the type is marked as a performance problem (is it hanging? something else?).

**Comment by vishalverma116** [comment]
hi @jakebailey , 
i apologies for being late.
i think this can help.

Language server is set to Microsoft.
Acquiring model 'intellisense-members-lstm' for python
Querying IntelliCode service for available models.
vs-intellicode-python was passed a model: {}.
Downloading model.
Starting download of https://cdsmprodstg.blob.core.windows.net/models-prod-output/Output_15708AE89896CA5DF1690433B7A8D93D28B7_215F8B4FAB1F4663ABD624559FD205B9?sv=2018-03-28&sr=b&sig=DhkEP3943NnZqQtBK8JQb7Ljz4HNO29SIObke0X1lU8%3D&se=2021-01-10T15%3A23%3A17Z&sp=r
Download complete.
Error while activating Python: {}

**Comment by jakebailey** [comment]
These are the for IntelliCode, but IntelliCode itself doesn't actually do anything, Pylance does (if you're using that). Do you have logs from the "python language server" output window?

**Comment by vishalverma116** [comment]
these are the logs from output of "python", 

at f.getInitializationOptions (/home/vishalverma116/.vscode/extensions/ms-python.python-2020.12.424452561/out/client/extension.js:59:35520)
	at f.getAnalysisOptions (/home/vishalverma116/.vscode/extensions/ms-python.python-2020.12.424452561/out/client/extension.js:9:273787)
	at /home/vishalverma116/.vscode/extensions/ms-python.python-2020.12.424452561/out/client/extension.js:1:64517
	at Object.t.tracing (/home/vishalverma116/.vscode/extensions/ms-python.python-2020.12.424452561/out/client/extension.js:1:50205)
	at f.r.value (/home/vishalverma116/.vscode/extensions/ms-python.python-2020.12.424452561/out/client/extension.js:1:64493)
	at r.startLanguageServer (/home/vishalverma116/.vscode/extensions/ms-python.python-2020.12.424452561/out/client/extension.js:59:53073)
	at /home/vishalverma116/.vscode/extensions/ms-python.python-2020.12.424452561/out/client/extension.js:1:64517
	at Object.t.tracing (/home/vishalverma116/.vscode/extensions/ms-python.python-2020.12.424452561/out/client/extension.js:1:50205)
	at r.value (/home/vishalverma116/.vscode/extensions/ms-python.python-2020.12.424452561/out/client/extension.js:1:64493)
	at r.l.value (/home/vishalverma116/.vscode/extensions/ms-python.python-2020.12.424452561/out/client/extension.js:1:9972)
	at restartLanguageServer (/home/vishalverma116/.vscode/extensions/ms-python.python-2020.12.424452561/out/client/extension.js:59:52913)
	at /home/vishalverma116/.vscode/extensions/ms-python.python-2020.12.424452561/out/client/extension.js:1:64517
	at Object.t.tracing (/home/vishalverma116/.vscode/extensions/ms-python.python-2020.12.424452561/out/client/extension.js:1:50205)
	at r.value (/home/vishalverma116/.vscode/extensions/ms-python.python-2020.12.424452561/out/client/extension.js:1:64493)
	at /home/vishalverma116/.vscode/extensions/ms-python.python-2020.12.424452561/out/client/extension.js:1:64517
	at Object.t.tracing (/home/vishalverma116/.vscode/extensions/ms-python.python-2020.12.424452561/out/client/extension.js:1:50205)
	at r.value (/home/vishalverma116/.vscode/extensions/ms-python.python-2020.12.424452561/out/client/extension.js:1:64493)
	at restartLanguageServerDebounced (/home/vishalverma116/.vscode/extensions/ms-python.python-2020.12.424452561/out/client/extension.js:59:52784)
	at r.<anonymous> (/home/vishalverma116/.vscode/extensions/ms-python.python-2020.12.424452561/out/client/extension.js:1:62420)
	at y (/home/vishalverma116/.vscode/extensions/ms-python.python-2020.12.424452561/out/client/extension.js:44:108829)
	at w (/home/vishalverma116/.vscode/extensions/ms-python.python-2020.12.424452561/out/client/extension.js:44:109104)
	at Timeout.E [as _onTimeout] (/home/vishalverma116/.vscode/extensions/ms-python.python-2020.12.424452561/out/client/extension.js:44:108994)
	at listOnTimeout (internal/timers.js:531:17)
	at processTimers (internal/timers.js:475:7)]
Error 2021-01-14 17:11:39: Failed to restart language server, Class name = r, completed in 15ms, has a falsy return value, , Return Value: undefined [Error: did not find an active interpreter

"python language server" does not give any output on output window. it is blank.

**Comment by jakebailey** [comment]
That output implies things failed because you don't have a Python interpreter selected. Do you have one selected at the bottom left, or is it saying there isn't one?

**Comment by ayim** [comment]
Hey @vishalverma116, we'd love to hear from you if you're still seeing this issue.
Feel free to open a new issue, going to close this one
