### ISSUE TITLE
"Language server extension command failed. Exception: Error: command 'python.intellicode.loadLanguageServerExtension' not found"

### ISSUE THREAD

**Issue by mj-crabtree** [MicrosoftDocs/intellicode#296]
> Sorry, something went wrong activating IntelliCode support for Python. Please check the "Python" and "VS IntelliCode" output windows for details.

![image](https://user-images.githubusercontent.com/66781848/120735527-aaac3e80-c4e2-11eb-8087-69209c0565c7.png)

from settings.json: `"pylance.insidersChannel": "off",`

```
Language server is set to "Default". Pylance is used as current language server.
Acquiring model
Acquiring model 'intellisense-members-lstm-pylance' for python
Querying IntelliCode service for available models.
vs-intellicode-python was passed a model: {}.
Cached model is up to date.
Activating Python extension
Language server extension command failed. Exception: Error: command 'python.intellicode.loadLanguageServerExtension' not found
    at p._tryExecuteCommand (file:///C:/Users/user/AppData/Local/Programs/Microsoft VS Code Insiders/resources/app/out/vs/workbench/workbench.desktop.main.js:1809:3360)
    at file:///C:/Users/user/AppData/Local/Programs/Microsoft VS Code Insiders/resources/app/out/vs/workbench/workbench.desktop.main.js:1809:3241
    at processTicksAndRejections (internal/process/task_queues.js:93:5)
Error while activating Python: {}
```

**Product and Version** [VS/VSCode]:
```
Visual Studio Code - Insiders
Version: 1.57.0-insider (user setup)
Commit: a62df5d6c53e844bfdc50694f943c3f34b6ff50e
Date: 2021-06-03T17:38:02.890Z (8 hrs ago)
Electron: 12.0.9
Chrome: 89.0.4389.128
Node.js: 14.16.0
V8: 8.9.255.25-electron.0
OS: Windows_NT x64 10.0.19043
```

**OS Version** [macOS/Windows]: win10 19043.1023
**IntelliCode Extension Version**: 1.2.14
**Target Platform or Language**: Python 3.9.5 (tags/v3.9.5:0a7dcbd, May  3 2021, 17:27:52) [MSC v.1928 64 bit (AMD64)] on win32
**Python extension**: v2021.5.842923320
**Pylance extension**: v2021.6.0

**Steps to Reproduce / Scenario:**
1. load a python file as if to edit
2. wait!

**Comment by ayim** [comment]
Hi @mj-crabtree, thanks for checking in with us about this issue.
I tried to repro with the same Python/Pylance/VSCode Insiders versions and wasn't able to run into this issue.

Has this issue happened again for you?

**Comment by mj-crabtree** [comment]
hi! 

the issue seems to be persisting. i've since reinstalled python, ensured it's present in path, insiders has been updated and no update extensions are available on my end. if there's anything you'd like to see then let me know!

looking through the python output, this keeps cropping up when opening python files

```
Starting Pylance language server.
Error 2021-06-07 20:27:02: Starting language server, Class name = r, completed in 1ms, has a falsy return value, , Return Value: undefined TypeError: Cannot read property 'onDidOpenNotebookDocument' of undefined
    at l.get onDidOpenNotebookDocument [as onDidOpenNotebookDocument] (c:\Users\crabtree\.vscode-insiders\extensions\ms-python.python-2021.5.842923320\out\client\extension.js:78:180874)
    at new a (c:\Users\crabtree\.vscode-insiders\extensions\ms-python.python-2021.5.842923320\out\client\extension.js:59:183978)
    at new t.NotebookMiddlewareAddon (c:\Users\crabtree\.vscode-insiders\extensions\ms-python.python-2021.5.842923320\out\client\extension.js:59:178815)
    at new y (c:\Users\crabtree\.vscode-insiders\extensions\ms-python.python-2021.5.842923320\out\client\extension.js:9:440208)
    at r.startLanguageServer (c:\Users\crabtree\.vscode-insiders\extensions\ms-python.python-2021.5.842923320\out\client\extension.js:59:240168)
    ```

**Comment by karbassi** [comment]
As @mj-crabtree has noted, it's still persisting.

<details>
<summary>python output</summary>

```
Starting Pylance language server.
Error 2021-06-09 14:26:24: Starting language server, Class name = r, completed in 0ms, has a falsy return value, , Return Value: undefined TypeError: Cannot read property 'onDidOpenNotebookDocument' of undefined
    at l.get onDidOpenNotebookDocument [as onDidOpenNotebookDocument] (/Users/ali/.vscode-insiders/extensions/ms-python.python-2021.5.842923320/out/client/extension.js:78:180874)
    at new a (/Users/ali/.vscode-insiders/extensions/ms-python.python-2021.5.842923320/out/client/extension.js:59:183978)
    at new t.NotebookMiddlewareAddon (/Users/ali/.vscode-insiders/extensions/ms-python.python-2021.5.842923320/out/client/extension.js:59:178815)
    at new y (/Users/ali/.vscode-insiders/extensions/ms-python.python-2021.5.842923320/out/client/extension.js:9:440208)
    at r.startLanguageServer (/Users/ali/.vscode-insiders/extensions/ms-python.python-2021.5.842923320/out/client/extension.js:59:240168)
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (internal/process/task_queues.js:93:5)
Error 2021-06-09 14:26:24: Failed to start language server, Class name = r, completed in 91ms, has a falsy return value, Arg 1: <Uri:/REDACTED.py>, Arg 2: {"architecture":3,"path":"/usr/local/bin/python3","version":{"options":{"loose":false,"includePrerelease":false},"loose":false,"raw":"3.9.5","major":3,"minor":9,"patch":5,"prerelease":[],"build":[],"version":"3.9.5"},"sysVersion":"3.9.5 (default, May  4 2021, 03:36:27) \n[Clang 12.0.0 (clang-1200.0.32.29)]","sysPrefix":"/usr/local/opt/python@3.9/Frameworks/Python.framework/Versions/3.9","fileHash":"ea68601707ab2036492552d81dd97d9cb75b0a4ad8bc44c2ce711a3689b91d22f61fa0dceb4deef96f47b1141fc419b72a4d2e9636f782673dc413e591834e70","envType":"Unknown","displayName":"Python 3.9.5 64-bit"}, Return Value: undefined TypeError: Cannot read property 'onDidOpenNotebookDocument' of undefined
    at l.get onDidOpenNotebookDocument [as onDidOpenNotebookDocument] (/Users/ali/.vscode-insiders/extensions/ms-python.python-2021.5.842923320/out/client/extension.js:78:180874)
    at new a (/Users/ali/.vscode-insiders/extensions/ms-python.python-2021.5.842923320/out/client/extension.js:59:183978)
    at new t.NotebookMiddlewareAddon (/Users/ali/.vscode-insiders/extensions/ms-python.python-2021.5.842923320/out/client/extension.js:59:178815)
    at new y (/Users/ali/.vscode-insiders/extensions/ms-python.python-2021.5.842923320/out/client/extension.js:9:440208)
    at r.startLanguageServer (/Users/ali/.vscode-insiders/extensions/ms-python.python-2021.5.842923320/out/client/extension.js:59:240168)
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (internal/process/task_queues.js:93:5)
Error 2021-06-09 14:26:24: TypeError: Cannot read property 'onDidOpenNotebookDocument' of undefined
    at l.get onDidOpenNotebookDocument [as onDidOpenNotebookDocument] (/Users/ali/.vscode-insiders/extensions/ms-python.python-2021.5.842923320/out/client/extension.js:78:180874)
    at new a (/Users/ali/.vscode-insiders/extensions/ms-python.python-2021.5.842923320/out/client/extension.js:59:183978)
    at new t.NotebookMiddlewareAddon (/Users/ali/.vscode-insiders/extensions/ms-python.python-2021.5.842923320/out/client/extension.js:59:178815)
    at new y (/Users/ali/.vscode-insiders/extensions/ms-python.python-2021.5.842923320/out/client/extension.js:9:440208)
    at r.startLanguageServer (/Users/ali/.vscode-insiders/extensions/ms-python.python-2021.5.842923320/out/client/extension.js:59:240168)
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (internal/process/task_queues.js:93:5)
We encountered an issue starting the language server. Reverting to Jedi language engine. Check the Python output panel for details.
Error 2021-06-09 14:26:24: Failed to activate language server, Class name = a, completed in 92ms, has a falsy return value, Arg 1: <Uri:/REDACTED.py>, Arg 2: {"architecture":3,"path":"/usr/local/bin/python3","version":{"options":{"loose":false,"includePrerelease":false},"loose":false,"raw":"3.9.5","major":3,"minor":9,"patch":5,"prerelease":[],"build":[],"version":"3.9.5"},"sysVersion":"3.9.5 (default, May  4 2021, 03:36:27) \n[Clang 12.0.0 (clang-1200.0.32.29)]","sysPrefix":"/usr/local/opt/python@3.9/Frameworks/Python.framework/Versions/3.9","fileHash":"ea68601707ab2036492552d81dd97d9cb75b0a4ad8bc44c2ce711a3689b91d22f61fa0dceb4deef96f47b1141fc419b72a4d2e9636f782673dc413e591834e70","envType":"Unknown","displayName":"Python 3.9.5 64-bit"}, Return Value: undefined TypeError: Cannot read property 'onDidOpenNotebookDocument' of undefined
    at l.get onDidOpenNotebookDocument [as onDidOpenNotebookDocument] (/Users/ali/.vscode-insiders/extensions/ms-python.python-2021.5.842923320/out/client/extension.js:78:180874)
    at new a (/Users/ali/.vscode-insiders/extensions/ms-python.python-2021.5.842923320/out/client/extension.js:59:183978)
    at new t.NotebookMiddlewareAddon (/Users/ali/.vscode-insiders/extensions/ms-python.python-2021.5.842923320/out/client/extension.js:59:178815)
    at new y (/Users/ali/.vscode-insiders/extensions/ms-python.python-2021.5.842923320/out/client/extension.js:9:440208)
    at r.startLanguageServer (/Users/ali/.vscode-insiders/extensions/ms-python.python-2021.5.842923320/out/client/extension.js:59:240168)
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (internal/process/task_queues.js:93:5)
```

</details>

<details>
<summary>VS IntelliCode</summary>

```
Language server is set to Pylance.
Acquiring model
Acquiring model 'intellisense-members-lstm-pylance' for python
Querying IntelliCode service for available models.
vs-intellicode-python was passed a model: {}.
Cached model is up to date.
Activating Python extension
Language server extension command failed. Exception: Error: command 'python.intellicode.loadLanguageServerExtension' not found
    at p._tryExecuteCommand (file:///Applications/Visual Studio Code - Insiders.app/Contents/Resources/app/out/vs/workbench/workbench.desktop.main.js:1809:3360)
    at file:///Applications/Visual Studio Code - Insiders.app/Contents/Resources/app/out/vs/workbench/workbench.desktop.main.js:1809:3241
    at processTicksAndRejections (internal/process/task_queues.js:93:5)
Error while activating Python: {}
```

</details>

<details>
<summary>Information</summary>

```
Version: 1.57.0-insider
Commit: b4c1bd0a9b03c749ea011b06c6d2676c8091a70c
Date: 2021-06-09T10:41:06.148Z
Electron: 12.0.9
Chrome: 89.0.4389.128
Node.js: 14.16.0
V8: 8.9.255.25-electron.0
OS: Darwin x64 20.5.0
```

```
Name: Python
Id: ms-python.python
Version: 2021.5.842923320
```

```
Name: Pylance
Id: ms-python.vscode-pylance
Version: 2021.6.0
```

```
Name: Visual Studio IntelliCode
Id: visualstudioexptteam.vscodeintellicode
Version: 1.2.14
```

</details>

**Comment by karbassi** [comment]
Related to #295

**Comment by ayim** [comment]
Hi there! Aaron from the Intellicode team here - we're looking into this.

Repro'd in...

VS Code 1.57.0 and 1.57.0-insider.
Python: v2021.5.842923320
Pylance: v2021.6.1
OS: Windows 10 21H1 Build 19043.1057

**Comment by ayim** [comment]
@karbassi @mj-crabtree 

Please upgrade to 2021.5.926500501 of the Python extension and let us know if the issue persists!
[marketplace.visualstudio.com/_apis/public/gallery/publishers/ms-python/vsextensions/python/2021.5.926500501/vspackage](url)

**Comment by mj-crabtree** [comment]
```
Language server is set to Pylance.
Acquiring model
Acquiring model 'intellisense-members-lstm-pylance' for python
Querying IntelliCode service for available models.
vs-intellicode-python was passed a model: {}.
Cached model is up to date.
Activating Python extension
```

looks good on my end! no issues to speak of from from intellicode or python.

**Comment by karbassi** [comment]
@ayim Fixed on my end as well. 🎉
