### ISSUE TITLE
Problem 

### ISSUE THREAD

**Issue by KelvemC** [MicrosoftDocs/intellicode#299]
Sorry, something went wrong activating IntelliCode support for Python. Please check the "Python" and "VS IntelliCode" output windows for details.

Output python:
User belongs to experiment group 'pythonaacf'
User belongs to experiment group 'pythonJoinMailingListVar3'
User belongs to experiment group 'pythonJediLSP'
User belongs to experiment group 'pythonDiscoveryModuleWithoutWatcher'
User belongs to experiment group 'pythonTensorboardExperiment'
User belongs to experiment group 'pythonSurveyNotificationcf'
User belongs to experiment group 'PythonPyTorchProfiler'
User belongs to experiment group 'CollectLSRequestTiming - control'
User belongs to experiment group 'CollectNodeLSRequestTiming - experiment'
Python interpreter path: ~\AppData\Local\Programs\Python\Python39\python.exe
Error 2021-06-10 16:05:43: Failed to check if file needs to be fixed [EntryNotFound (FileSystemError): Unable to read file 'c:\Users\Micro\Desktop\AULAS IF\ANOTAÇÕES E ATV PYTHON\.vscode\settings.json' (Error: Unable to resolve non-existing file 'c:\Users\Micro\Desktop\AULAS IF\ANOTAÇÕES E ATV PYTHON\.vscode\settings.json')
	at _handleError (c:\Users\Micro\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:84:155538)
	at processTicksAndRejections (internal/process/task_queues.js:93:5)
	at async y.readText (c:\Users\Micro\.vscode\extensions\ms-python.python-2021.5.842923320\out\client\extension.js:9:344717)
	at async p.doesFileNeedToBeFixed (c:\Users\Micro\.vscode\extensions\ms-python.python-2021.5.842923320\out\client\extension.js:59:581560)
	at async c:\Users\Micro\.vscode\extensions\ms-python.python-2021.5.842923320\out\client\extension.js:59:580687
	at async Promise.all (index 1)
	at async p.getFilesToBeFixed (c:\Users\Micro\.vscode\extensions\ms-python.python-2021.5.842923320\out\client\extension.js:59:580633)
	at async p.updateTestSettings (c:\Users\Micro\.vscode\extensions\ms-python.python-2021.5.842923320\out\client\extension.js:59:580260)] {
  code: 'FileNotFound'
}
Starting Pylance language server.
Error 2021-06-10 16:05:43: Starting language server, Class name = r, completed in 1ms, has a falsy return value, , Return Value: undefined [TypeError: Cannot read property 'onDidOpenNotebookDocument' of undefined
	at l.get onDidOpenNotebookDocument [as onDidOpenNotebookDocument] (c:\Users\Micro\.vscode\extensions\ms-python.python-2021.5.842923320\out\client\extension.js:78:180874)
	at new a (c:\Users\Micro\.vscode\extensions\ms-python.python-2021.5.842923320\out\client\extension.js:59:183978)
	at new t.NotebookMiddlewareAddon (c:\Users\Micro\.vscode\extensions\ms-python.python-2021.5.842923320\out\client\extension.js:59:178815)
	at new y (c:\Users\Micro\.vscode\extensions\ms-python.python-2021.5.842923320\out\client\extension.js:9:440208)
	at r.startLanguageServer (c:\Users\Micro\.vscode\extensions\ms-python.python-2021.5.842923320\out\client\extension.js:59:240168)]
Error 2021-06-10 16:05:43: Failed to start language server, Class name = r, completed in 3ms, has a falsy return value, Arg 1: <Uri:c:\Users\Micro\Desktop\AULAS IF\ANOTAÇÕES E ATV PYTHON\NovaATVpy\Q1.py>, Arg 2: {"sysPrefix":"C:\\Users\\Micro\\AppData\\Local\\Programs\\Python\\Python39","envType":"Unknown","envName":"","envPath":"","path":"C:\\Users\\Micro\\AppData\\Local\\Programs\\Python\\Python39\\python.exe","architecture":3,"sysVersion":"3.9.5 (tags/v3.9.5:0a7dcbd, May  3 2021, 17:27:52) [MSC v.1928 64 bit (AMD64)]","version":{"raw":"3.9.5","major":3,"minor":9,"patch":5,"build":[],"prerelease":["final","0"]},"companyDisplayName":"PythonCore","displayName":"Python 3.9.4 64-bit"}, Return Value: undefined [TypeError: Cannot read property 'onDidOpenNotebookDocument' of undefined
	at l.get onDidOpenNotebookDocument [as onDidOpenNotebookDocument] (c:\Users\Micro\.vscode\extensions\ms-python.python-2021.5.842923320\out\client\extension.js:78:180874)
	at new a (c:\Users\Micro\.vscode\extensions\ms-python.python-2021.5.842923320\out\client\extension.js:59:183978)
	at new t.NotebookMiddlewareAddon (c:\Users\Micro\.vscode\extensions\ms-python.python-2021.5.842923320\out\client\extension.js:59:178815)
	at new y (c:\Users\Micro\.vscode\extensions\ms-python.python-2021.5.842923320\out\client\extension.js:9:440208)
	at r.startLanguageServer (c:\Users\Micro\.vscode\extensions\ms-python.python-2021.5.842923320\out\client\extension.js:59:240168)]
Error 2021-06-10 16:05:43: [TypeError: Cannot read property 'onDidOpenNotebookDocument' of undefined
	at l.get onDidOpenNotebookDocument [as onDidOpenNotebookDocument] (c:\Users\Micro\.vscode\extensions\ms-python.python-2021.5.842923320\out\client\extension.js:78:180874)
	at new a (c:\Users\Micro\.vscode\extensions\ms-python.python-2021.5.842923320\out\client\extension.js:59:183978)
	at new t.NotebookMiddlewareAddon (c:\Users\Micro\.vscode\extensions\ms-python.python-2021.5.842923320\out\client\extension.js:59:178815)
	at new y (c:\Users\Micro\.vscode\extensions\ms-python.python-2021.5.842923320\out\client\extension.js:9:440208)
	at r.startLanguageServer (c:\Users\Micro\.vscode\extensions\ms-python.python-2021.5.842923320\out\client\extension.js:59:240168)]
We encountered an issue starting the language server. Reverting to Jedi language engine. Check the Python output panel for details.
Error 2021-06-10 16:05:43: Failed to activate language server, Class name = a, completed in 8ms, has a falsy return value, Arg 1: <Uri:c:\Users\Micro\Desktop\AULAS IF\ANOTAÇÕES E ATV PYTHON\NovaATVpy\Q1.py>, Arg 2: {"sysPrefix":"C:\\Users\\Micro\\AppData\\Local\\Programs\\Python\\Python39","envType":"Unknown","envName":"","envPath":"","path":"C:\\Users\\Micro\\AppData\\Local\\Programs\\Python\\Python39\\python.exe","architecture":3,"sysVersion":"3.9.5 (tags/v3.9.5:0a7dcbd, May  3 2021, 17:27:52) [MSC v.1928 64 bit (AMD64)]","version":{"raw":"3.9.5","major":3,"minor":9,"patch":5,"build":[],"prerelease":["final","0"]},"companyDisplayName":"PythonCore","displayName":"Python 3.9.4 64-bit"}, Return Value: undefined [TypeError: Cannot read property 'onDidOpenNotebookDocument' of undefined
	at l.get onDidOpenNotebookDocument [as onDidOpenNotebookDocument] (c:\Users\Micro\.vscode\extensions\ms-python.python-2021.5.842923320\out\client\extension.js:78:180874)
	at new a (c:\Users\Micro\.vscode\extensions\ms-python.python-2021.5.842923320\out\client\extension.js:59:183978)
	at new t.NotebookMiddlewareAddon (c:\Users\Micro\.vscode\extensions\ms-python.python-2021.5.842923320\out\client\extension.js:59:178815)
	at new y (c:\Users\Micro\.vscode\extensions\ms-python.python-2021.5.842923320\out\client\extension.js:9:440208)
	at r.startLanguageServer (c:\Users\Micro\.vscode\extensions\ms-python.python-2021.5.842923320\out\client\extension.js:59:240168)]
> ~\AppData\Local\Programs\Python\Python39\python.exe c:\Users\Micro\.vscode\extensions\ms-python.python-2021.5.842923320\pythonFiles\pyvsc-run-isolated.py -c "import sys;print(sys.prefix)"
cwd: c:\Users\Micro\Desktop\AULAS IF\ANOTAÇÕES E ATV PYTHON
> ~\AppData\Local\Programs\Python\Python39\python.exe c:\Users\Micro\.vscode\extensions\ms-python.python-2021.5.842923320\pythonFiles\pyvsc-run-isolated.py -c "import sys;print(sys.prefix)"
cwd: c:\Users\Micro\Desktop\AULAS IF\ANOTAÇÕES E ATV PYTHON
> ~\AppData\Local\Programs\Python\Python39\python.exe c:\Users\Micro\.vscode\extensions\ms-python.python-2021.5.842923320\pythonFiles\pyvsc-run-isolated.py -c "import sys;print(sys.executable)"
cwd: c:\Users\Micro\Desktop\AULAS IF\ANOTAÇÕES E ATV PYTHON
> ~\AppData\Local\Programs\Python\Python39\python.exe c:\Users\Micro\.vscode\extensions\ms-python.python-2021.5.842923320\pythonFiles\pyvsc-run-isolated.py -c "import sys;print(sys.executable)"
cwd: c:\Users\Micro\Desktop\AULAS IF\ANOTAÇÕES E ATV PYTHON
> ~\AppData\Local\Programs\Python\Python39\python.exe c:\Users\Micro\.vscode\extensions\ms-python.python-2021.5.842923320\pythonFiles\pyvsc-run-isolated.py -c "from distutils.sysconfig import get_python_lib; print(get_python_lib())"
cwd: c:\Users\Micro\Desktop\AULAS IF\ANOTAÇÕES E ATV PYTHON
> ~\AppData\Local\Programs\Python\Python39\python.exe c:\Users\Micro\.vscode\extensions\ms-python.python-2021.5.842923320\pythonFiles\pyvsc-run-isolated.py -c "from distutils.sysconfig import get_python_lib; print(get_python_lib())"
cwd: c:\Users\Micro\Desktop\AULAS IF\ANOTAÇÕES E ATV PYTHON
> ~\AppData\Local\Programs\Python\Python39\python.exe c:\Users\Micro\.vscode\extensions\ms-python.python-2021.5.842923320\pythonFiles\pyvsc-run-isolated.py site --user-site
cwd: c:\Users\Micro\Desktop\AULAS IF\ANOTAÇÕES E ATV PYTHON
> ~\AppData\Local\Programs\Python\Python39\python.exe c:\Users\Micro\.vscode\extensions\ms-python.python-2021.5.842923320\pythonFiles\pyvsc-run-isolated.py site --user-site
cwd: c:\Users\Micro\Desktop\AULAS IF\ANOTAÇÕES E ATV PYTHON
> ~\AppData\Local\Programs\Python\Python39\python.exe c:\Users\Micro\.vscode\extensions\ms-python.python-2021.5.842923320\pythonFiles\pyvsc-run-isolated.py c:\Users\Micro\.vscode\extensions\ms-python.python-2021.5.842923320\pythonFiles\completion.py
> ~\AppData\Local\Programs\Python\Python39\python.exe c:\Users\Micro\.vscode\extensions\ms-python.python-2021.5.842923320\pythonFiles\pyvsc-run-isolated.py c:\Users\Micro\.vscode\extensions\ms-python.python-2021.5.842923320\pythonFiles\completion.py
> conda --version

Output Intellicode:

Language server is set to "Default". Pylance is used as current language server.
Acquiring model
Acquiring model 'intellisense-members-lstm-pylance' for python
Querying IntelliCode service for available models.
vs-intellicode-python was passed a model: {}.
Cached model is up to date.
Activating Python extension
Language server extension command failed. Exception: Error: command 'python.intellicode.loadLanguageServerExtension' not found
    at p._tryExecuteCommand (file:///C:/Users/Micro/AppData/Local/Programs/Microsoft VS Code/resources/app/out/vs/workbench/workbench.desktop.main.js:1809:3360)
    at file:///C:/Users/Micro/AppData/Local/Programs/Microsoft VS Code/resources/app/out/vs/workbench/workbench.desktop.main.js:1809:3241
    at processTicksAndRejections (internal/process/task_queues.js:93:5)
Error while activating Python: {}

**Comment by ayim** [comment]
@KelvemC @Kubo-SVK @Tes3awy

Please upgrade to 2021.5.926500501 of the Python extension and let us know if the issue persists!
[marketplace.visualstudio.com/_apis/public/gallery/publishers/ms-python/vsextensions/python/2021.5.926500501/vspackage](url)

**Comment by Kubo-SVK** [comment]
Works fine for me. No more errors.
