### ISSUE TITLE
[renderer1] [error] Already at root scope: Error: Already at root scope

### ISSUE THREAD

**Issue by vladivanov20** [MicrosoftDocs/intellicode#346]
Issue Type: <b>Bug</b>

Full Trace:
```
_[renderer1] [error] Already at root scope: Error: Already at root scope
    at a.current (/home/vladivanov20/.vscode/extensions/visualstudioexptteam.intellicode-api-usage-examples-0.0.10/dist/extension.js:2:30611)
    at a.getParentClass (/home/vladivanov20/.vscode/extensions/visualstudioexptteam.intellicode-api-usage-examples-0.0.10/dist/extension.js:2:30760)
    at o.visit_identifier (/home/vladivanov20/.vscode/extensions/visualstudioexptteam.intellicode-api-usage-examples-0.0.10/dist/extension.js:2:31770)
    at o.visit (/home/vladivanov20/.vscode/extensions/visualstudioexptteam.intellicode-api-usage-examples-0.0.10/dist/extension.js:1:36059)
    at o.genericVisit (/home/vladivanov20/.vscode/extensions/visualstudioexptteam.intellicode-api-usage-examples-0.0.10/dist/extension.js:1:36145)
    at o.visit (/home/vladivanov20/.vscode/extensions/visualstudioexptteam.intellicode-api-usage-examples-0.0.10/dist/extension.js:1:36068)
    at o.visit_function_definition (/home/vladivanov20/.vscode/extensions/visualstudioexptteam.intellicode-api-usage-examples-0.0.10/dist/extension.js:2:31574)
    at o.visit (/home/vladivanov20/.vscode/extensions/visualstudioexptteam.intellicode-api-usage-examples-0.0.10/dist/extension.js:1:36059)
    at s.visit_function_definition (/home/vladivanov20/.vscode/extensions/visualstudioexptteam.intellicode-api-usage-examples-0.0.10/dist/extension.js:17:224227)
    at s.visit (/home/vladivanov20/.vscode/extensions/visualstudioexptteam.intellicode-api-usage-examples-0.0.10/dist/extension.js:1:36059)
    at s.genericVisit (/home/vladivanov20/.vscode/extensions/visualstudioexptteam.intellicode-api-usage-examples-0.0.10/dist/extension.js:1:36145)
    at s.visit (/home/vladivanov20/.vscode/extensions/visualstudioexptteam.intellicode-api-usage-examples-0.0.10/dist/extension.js:1:36068)
    at u.resolveTypes (/home/vladivanov20/.vscode/extensions/visualstudioexptteam.intellicode-api-usage-examples-0.0.10/dist/extension.js:17:222704)
    at u.extract (/home/vladivanov20/.vscode/extensions/visualstudioexptteam.intellicode-api-usage-examples-0.0.10/dist/extension.js:17:221999)
    at c.addOrUpdateDocument (/home/vladivanov20/.vscode/extensions/visualstudioexptteam.intellicode-api-usage-examples-0.0.10/dist/extension.js:17:30530)
    at t.EditorState.addOrUpdateDocument (/home/vladivanov20/.vscode/extensions/visualstudioexptteam.intellicode-api-usage-examples-0.0.10/dist/extension.js:17:583398)
    at t.EditorState.changedEditorText (/home/vladivanov20/.vscode/extensions/visualstudioexptteam.intellicode-api-usage-examples-0.0.10/dist/extension.js:17:582904)
    at /home/vladivanov20/.vscode/extensions/visualstudioexptteam.intellicode-api-usage-examples-0.0.10/dist/extension.js:17:51881
    at u.invoke (/usr/share/code/resources/app/out/vs/workbench/api/node/extensionHostProcess.js:58:145)
    at v.fire (/usr/share/code/resources/app/out/vs/workbench/api/node/extensionHostProcess.js:58:1856)
    at R.$acceptModelChanged (/usr/share/code/resources/app/out/vs/workbench/api/node/extensionHostProcess.js:85:72788)
    at i._doInvokeHandler (/usr/share/code/resources/app/out/vs/workbench/api/node/extensionHostProcess.js:89:13826)
    at i._invokeHandler (/usr/share/code/resources/app/out/vs/workbench/api/node/extensionHostProcess.js:89:13510)
    at i._receiveRequest (/usr/share/code/resources/app/out/vs/workbench/api/node/extensionHostProcess.js:89:12171)
    at i._receiveOneMessage (/usr/share/code/resources/app/out/vs/workbench/api/node/extensionHostProcess.js:89:10841)
    at /usr/share/code/resources/app/out/vs/workbench/api/node/extensionHostProcess.js:89:8947
    at u.invoke (/usr/share/code/resources/app/out/vs/workbench/api/node/extensionHostProcess.js:58:145)
    at v.fire (/usr/share/code/resources/app/out/vs/workbench/api/node/extensionHostProcess.js:58:1856)
    at d.fire (/usr/share/code/resources/app/out/vs/workbench/api/node/extensionHostProcess.js:66:19034)
    at /usr/share/code/resources/app/out/vs/workbench/api/node/extensionHostProcess.js:104:34275
    at u.invoke (/usr/share/code/resources/app/out/vs/workbench/api/node/extensionHostProcess.js:58:145)
    at v.fire (/usr/share/code/resources/app/out/vs/workbench/api/node/extensionHostProcess.js:58:1856)
    at d.fire (/usr/share/code/resources/app/out/vs/workbench/api/node/extensionHostProcess.js:66:19034)
    at o._receiveMessage (/usr/share/code/resources/app/out/vs/workbench/api/node/extensionHostProcess.js:66:23615)
    at /usr/share/code/resources/app/out/vs/workbench/api/node/extensionHostProcess.js:66:21149
    at u.invoke (/usr/share/code/resources/app/out/vs/workbench/api/node/extensionHostProcess.js:58:145)
    at v.fire (/usr/share/code/resources/app/out/vs/workbench/api/node/extensionHostProcess.js:58:1856)
    at v.acceptChunk (/usr/share/code/resources/app/out/vs/workbench/api/node/extensionHostProcess.js:66:15865)
    at /usr/share/code/resources/app/out/vs/workbench/api/node/extensionHostProcess.js:66:14995
    at Socket.P (/usr/share/code/resources/app/out/vs/workbench/api/node/extensionHostProcess.js:104:13797)
    at Socket.emit (node:events:390:28)
    at addChunk (node:internal/streams/readable:315:12)
    at readableAddChunk (node:internal/streams/readable:289:9)
    at Socket.Readable.push (node:internal/streams/readable:228:10)
    at Pipe.onStreamRead (node:internal/stream_base_commons:199:23)_
```

Steps to replicate:
1. Install extension
2. Create python file
3. Start writing the following snippet:
```
import numpy as np
np.random.randint()
```
4. Check your Output window (Log (Window))

Extension version: 1.2.18
VS Code version: Code 1.66.0 (e18005f0f1b33c29e81d732535d8c0e47cafb0b5, 2022-03-30T05:50:41.156Z)
OS version: Linux x64 5.4.0-81-generic
Restricted Mode: No

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-1065G7 CPU @ 1.30GHz (8 x 3312)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: disabled_off<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>opengl: enabled_on<br>rasterization: disabled_software<br>raw_draw: disabled_off_ok<br>skia_renderer: enabled_on<br>video_decode: disabled_software<br>video_encode: disabled_software<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|3, 2, 2|
|Memory (System)|7.55GB (0.29GB free)|
|Process Argv|--unity-launch --crash-reporter-id b471123b-74f8-43bf-b24a-9be1569d32c7|
|Screen Reader|no|
|VM|0%|
|DESKTOP_SESSION|ubuntu|
|XDG_CURRENT_DESKTOP|Unity|
|XDG_SESSION_DESKTOP|ubuntu|
|XDG_SESSION_TYPE|x11|
</details>

**Comment by DavidObando** [comment]
@osobeso can you please take a look at this?

**Comment by vladivanov20** [comment]
Hey @osobeso @DavidObando! Any updates? Thank you :)

**Comment by vladivanov20** [comment]
@osobeso @DavidObando Any updates on this issue? Thanks!

**Comment by osobeso** [comment]
@vladivanov20 the responsible team is looking into it, we will update the ticket once we have published a fix.
Thanks!

**Comment by vladivanov20** [comment]
Thank you!

**Comment by osobeso** [comment]
@vladivanov20 Hi, we have updated the extension with a patch that fixes this issue.
Thanks for the feedback, I will close the issue for now but please let us know if you still have any issues.

**Comment by vladivanov20** [comment]
Thank you! Appreciate it
