### ISSUE TITLE
Something went activating Intellicode support for python

### ISSUE THREAD

**Issue by FendaRoadz** [MicrosoftDocs/intellicode#348]
VS Code 1.66.1
Windows 10
IntelliCode 1.2.18
Python 3.10.4

Hello, i have the issue with IntelliCode. When i open VS Code and extensions are loading, the message "Something went activating Intellicode support for python" pops out. 
I read couple similar issues but did not found the solution. I reinstalled all python related and vs code and all the extensions.
Please help, thanx in advance!

  Language server is set to Pylance.
  Acquiring model
  Acquiring model 'intellisense-members-lstm-pylance' for python
  Querying IntelliCode service for available models.
  vs-intellicode-python was passed a model: {}.
  Cached model is up to date.
  Activating Python extension
  Language server extension command failed. Exception: Error: Connection got disposed.
	  at Object.dispose (c:\Users\fenda\.vscode\extensions\ms-python.python-2022.4.1\out\client\extension.js:47:145778)
	  at Object.dispose (c:\Users\fenda\.vscode\extensions\ms-python.python-2022.4.1\out\client\extension.js:24:155505)
	  at S.handleConnectionClosed (c:\Users\fenda\.vscode\extensions\ms-python.python-2022.4.1\out\client\extension.js:24:155717)
	  at S.handleConnectionClosed (c:\Users\fenda\.vscode\extensions\ms-python.python-2022.4.1\out\client\extension.js:32:10622)
	  at t (c:\Users\fenda\.vscode\extensions\ms-python.python-2022.4.1\out\client\extension.js:24:153810)
	  at invoke (c:\Users\fenda\.vscode\extensions\ms-python.python-2022.4.1\out\client\extension.js:24:281735)
	  at o.fire (c:\Users\fenda\.vscode\extensions\ms-python.python-2022.4.1\out\client\extension.js:24:282496)
	  at X (c:\Users\fenda\.vscode\extensions\ms-python.python-2022.4.1\out\client\extension.js:47:135140)
	  at invoke (c:\Users\fenda\.vscode\extensions\ms-python.python-2022.4.1\out\client\extension.js:24:281735)
	  at o.fire (c:\Users\fenda\.vscode\extensions\ms-python.python-2022.4.1\out\client\extension.js:24:282496)
	  at d.fireClose (c:\Users\fenda\.vscode\extensions\ms-python.python-2022.4.1\out\client\extension.js:47:125209)
	  at ChildProcess.<anonymous> (c:\Users\fenda\.vscode\extensions\ms-python.python-2022.4.1\out\client\extension.js:24:277465)
	  at ChildProcess.emit (node:events:402:35)
	  at maybeClose (node:internal/child_process:1064:16)
	  at Process.ChildProcess._handle.onexit (node:internal/child_process:301:5)
  Error while activating Python: {}

Python output:   

Experiment 'pythonaa' is active
Experiment 'pythonTensorboardExperiment' is active
Experiment 'pythonSurveyNotificationcf' is active
Experiment 'PythonPyTorchProfiler' is active
Experiment 'pythonDeprecatePythonPath' is active
Experiment 'pythonInterpreterInfoPinned' is active
> conda info --json
> ~\AppData\Local\Microsoft\WindowsApps\python3.10.exe ~\.vscode\extensions\ms-python.python-2022.4.1\pythonFiles\get_output_via_markers.py ~\.vscode\extensions\ms-python.python-2022.4.1\pythonFiles\interpreterInfo.py
Python interpreter path: ~\AppData\Local\Microsoft\WindowsApps\python3.10.exe
> ~\AppData\Local\Programs\Python\Python310\python.exe ~\.vscode\extensions\ms-python.python-2022.4.1\pythonFiles\get_output_via_markers.py ~\.vscode\extensions\ms-python.python-2022.4.1\pythonFiles\interpreterInfo.py
Starting Pylance language server.

**Comment by DavidObando** [comment]
@luabud This looks like a Python LSP issue? Can you take a look?

**Comment by brettcannon** [comment]
This would belong at https://github.com/microsoft/pylance-release .

/cc @judej

**Comment by judej** [comment]
This looks like a dupe of https://github.com/microsoft/pylance-release/issues/2434
