### ISSUE TITLE
Intellicode doesn't work. it shows "Failed to load ONNX runtime. Exception Error: The specified module could not be found." in logs

### ISSUE THREAD

**Issue by erjiaxiao** [MicrosoftDocs/intellicode#401]
**Product and Version** [VS/VSCode]: VScode
**OS Version** [macOS/Windows]: Windows
**IntelliCode Extension Version**: 1.2.22
**Target Platform or Language** [e.g. Node.js]: Python

**Steps to Reproduce / Scenario:**

1. I Installed VScode
2. I Installed Conda
3. I Installed Pylance
4. I Installed Intellicode
5. it finished downloading the intellicode model

And the intellicode dosen't work properly. The following is the log message:

[Info  - 14:49:42] (12032) Pylance language server 2022.8.20 (pyright 888eb243) starting
[Info  - 14:49:42] (12032) Server root directory: c:\Users\ASUS\.vscode\extensions\ms-python.vscode-pylance-2022.8.20\dist
[Info  - 14:49:42] (12032) Starting service instance "test"
[Info  - 14:49:42] (12032) Notebook support: LSP
[Info  - 14:49:42] (12032) Interactive window support: LSP
[Info  - 14:49:42] (12032) No configuration file found.
[Info  - 14:49:42] (12032) No pyproject.toml file found.
[Info  - 14:49:42] (12032) Setting pythonPath for service "test": "F:\anaconda3\envs\test\python.exe"
[Warn  - 14:49:42] (12032) stubPath c:\Users\ASUS\Desktop\test\typings is not a valid directory.
[Info  - 14:49:42] (12032) Assuming Python version 3.10
[Info  - 14:49:42] (12032) Assuming Python platform Windows
[Info  - 14:49:43] (12032) Searching for source files
[Info  - 14:49:43] (12032) Found 1 source file
[Info  - 14:49:43] (12032) Background analysis(1) root directory: c:\Users\ASUS\.vscode\extensions\ms-python.vscode-pylance-2022.8.20\dist
[Info  - 14:49:43] (12032) Background analysis(1) started
[Error - 14:50:33] (12032) Failed to load ONNX runtime. Exception Error: The specified module could not be found.
\\?\c:\Users\ASUS\.vscode\extensions\ms-python.vscode-pylance-2022.8.20\dist\native\onnxruntime\napi-v3\win32\x64\onnxruntime_binding.node
    at process.func [as dlopen] (node:electron/js2c/asar_bundle:5:1812)
    at Object.Module._extensions..node (node:internal/modules/cjs/loader:1246:18)
    at Object.func [as .node] (node:electron/js2c/asar_bundle:5:1812)
    at Module.load (node:internal/modules/cjs/loader:1035:32)
    at Module._load (node:internal/modules/cjs/loader:876:12)
    at Function.c._load (node:electron/js2c/asar_bundle:5:13343)
    at Module.require (node:internal/modules/cjs/loader:1059:19)
    at require (node:internal/modules/cjs/helpers:102:18)
    at Module.82101 (c:\Users\ASUS\.vscode\extensions\ms-python.vscode-pylance-2022.8.20\dist\pylance-internal\node_modules\onnxruntime-node\dist\binding.js:1:24)
    at _0x213ee1 (c:\Users\ASUS\.vscode\extensions\ms-python.vscode-pylance-2022.8.20\dist\server.bundle.js:1:437701)
    at Object.2583 (c:\Users\ASUS\.vscode\extensions\ms-python.vscode-pylance-2022.8.20\dist\pylance-internal\node_modules\onnxruntime-node\dist\backend.js:20:19)
    at _0x213ee1 (c:\Users\ASUS\.vscode\extensions\ms-python.vscode-pylance-2022.8.20\dist\server.bundle.js:1:437701)
    at Object.96678 (c:\Users\ASUS\.vscode\extensions\ms-python.vscode-pylance-2022.8.20\dist\pylance-internal\node_modules\onnxruntime-node\dist\index.js:17:19)
    at _0x213ee1 (c:\Users\ASUS\.vscode\extensions\ms-python.vscode-pylance-2022.8.20\dist\server.bundle.js:1:437701)
    at _0x40699d.<computed>.initialize (c:\Users\ASUS\.vscode\extensions\ms-python.vscode-pylance-2022.8.20\dist\server.bundle.js:1:133262)
    at _0x51ec1f.result (c:\Users\ASUS\.vscode\extensions\ms-python.vscode-pylance-2022.8.20\dist\server.bundle.js:1:155454)
    at i (c:\Users\ASUS\.vscode\extensions\ms-python.vscode-pylance-2022.8.20\dist\pyright-internal\src\languageServerBase.ts:1247:19)
    at _0x241a35.onExecuteCommand (c:\Users\ASUS\.vscode\extensions\ms-python.vscode-pylance-2022.8.20\dist\pyright-internal\src\languageServerBase.ts:1279:13), Error code: ERR_DLOPEN_FAILED

**Comment by ayim** [comment]
@leti367 any idea what could be causing this?

**Comment by leti367** [comment]
Did a test on my x64 windows machine (win 11) seems I cannot reproduce this issue at this time.
Here are the extensions I have:
vscode 1.70.1
intellicode: v1.2.22
pylance: v2022.8.20
python:v2022.12.0

@erjiaxiao, can you help to check is your machine x64 or arm64?

**Comment by erjiaxiao** [comment]
Thanks for testing! my machine is x64 and it has been working for me for 10 years or so. Does this matter? I try my another machine also x64 which I brought back this year and intellicode works properly on it. @leti367

**Comment by leti367** [comment]
We haven't added the onnx-runtime support for arm64 windows yet, so if you use IntelliCode extension on an arm64 windows, you will definitely see similar errors. But since you are using x64 windows, that's not the case.

**Comment by erjiaxiao** [comment]
I see. maybe there is something wrong which is specific to my machine. and I can't reproduce it on my new machine too. so should we close this issue because it's so specific and can't be reproduced? @leti367

**Comment by ayim** [comment]
@erjiaxiao we'll keep this open to track this issue as we investigate :)

**Comment by fireattack** [comment]
I have this issue on a Win7 machine as well. OP, which version of Windows do you use?

**Comment by vivlimmsft** [comment]
Can you please copy & paste the contents of Help > About in VSCode? It's possible that you might be running the 32-bit version of VSCode.

**Comment by fireattack** [comment]
Here you go:
```
Version: 1.70.2 (system setup)
Commit: e4503b30fc78200f846c62cf8091b76ff5547662
Date: 2022-08-16T05:35:13.448Z
Electron: 18.3.5
Chromium: 100.0.4896.160
Node.js: 16.13.2
V8: 10.0.139.17-electron.0
OS: Windows_NT x64 6.1.7601
```

No, it's the 64-bit one.

**Comment by leti367** [comment]
We are using onnxruntime-node package, not sure if win 7 is supported in this case. I will take a look at the onnx runtime build process to see if I can find something, otherwise we can open an issue to Onnx runtime repo.

**Comment by PrattayDev** [comment]
> Thanks for testing! my machine is x64 and it has been working for me for 10 years or so. Does this matter? I try my another machine also x64 which I brought back this year and intellicode works properly on it. @leti367

my laptop hp envy x64 but intellicode shows problem though i installed its says its not activating

**Comment by erjiaxiao** [comment]
Hello @PrattayDev, I try vscode and intellicode in the WSL Ubuntu and they work pretty well. You could try it!

**Comment by colorsakura** [comment]
i have same issue

PC: Lenovo Yoga14s intel

```
Version: 1.72.2 (user setup)
Commit: d045a5eda657f4d7b676dedbfa7aab8207f8a075
Date: 2022-10-12T22:15:18.074Z
Electron: 19.0.17
Chromium: 102.0.5005.167
Node.js: 16.14.2
V8: 10.2.154.15-electron.0
OS: Windows_NT x64 10.0.22621
Sandboxed: No
```

```
[Info  - 20:28:52] (4820) Pylance language server 2022.10.30 (pyright 50e12b4b) starting
[Info  - 20:28:52] (4820) Server root directory: c:\Users\iflyg\.vscode\extensions\ms-python.vscode-pylance-2022.10.30\dist
[Info  - 20:28:52] (4820) Starting service instance "irik"
[Info  - 20:28:52] (4820) Notebook support: Legacy
[Info  - 20:28:52] (4820) Interactive window support: Legacy
[Info  - 20:28:52] (4820) No configuration file found.
[Info  - 20:28:52] (4820) No pyproject.toml file found.
[Info  - 20:28:52] (4820) Setting pythonPath for service "irik": "d:\Github\irik\venv\Scripts\python.exe"
[Warn  - 20:28:52] (4820) stubPath d:\Github\irik\typings is not a valid directory.
[Info  - 20:28:52] (4820) Assuming Python version 3.10
[Info  - 20:28:52] (4820) Assuming Python platform Windows
[Info  - 20:28:52] (4820) Searching for source files
[Info  - 20:28:52] (4820) Auto-excluding d:\Github\irik\venv
[Info  - 20:28:52] (4820) Found 10 source files
[Info  - 20:28:52] (4820) Background analysis(1) root directory: c:\Users\iflyg\.vscode\extensions\ms-python.vscode-pylance-2022.10.30\dist
[Info  - 20:28:52] (4820) Background analysis(1) started
[Error - 20:28:54] (4820) Failed to load ONNX runtime. Exception Error: The specified module could not be found.
\\?\c:\Users\iflyg\.vscode\extensions\ms-python.vscode-pylance-2022.10.30\dist\native\onnxruntime\napi-v3\win32\x64\onnxruntime_binding.node
    at process.func [as dlopen] (node:electron/js2c/asar_bundle:5:1812)
    at Object.Module._extensions..node (node:internal/modules/cjs/loader:1250:18)
    at Object.func [as .node] (node:electron/js2c/asar_bundle:5:1812)
    at Module.load (node:internal/modules/cjs/loader:1035:32)
    at Module._load (node:internal/modules/cjs/loader:876:12)
    at Function.c._load (node:electron/js2c/asar_bundle:5:13343)
    at Module.require (node:internal/modules/cjs/loader:1059:19)
    at require (node:internal/modules/cjs/helpers:102:18)
    at Module.2101 (c:\Users\iflyg\.vscode\extensions\ms-python.vscode-pylance-2022.10.30\dist\pylance-internal\node_modules\onnxruntime-node\dist\binding.js:1:24)
    at _0x171273 (c:\Users\iflyg\.vscode\extensions\ms-python.vscode-pylance-2022.10.30\dist\server.bundle.js:1:422229)
    at Object.8035 (c:\Users\iflyg\.vscode\extensions\ms-python.vscode-pylance-2022.10.30\dist\pylance-internal\node_modules\onnxruntime-node\dist\backend.js:20:19)
    at _0x171273 (c:\Users\iflyg\.vscode\extensions\ms-python.vscode-pylance-2022.10.30\dist\server.bundle.js:1:422229)
    at Object.7844 (c:\Users\iflyg\.vscode\extensions\ms-python.vscode-pylance-2022.10.30\dist\pylance-internal\node_modules\onnxruntime-node\dist\index.js:17:19)
    at _0x171273 (c:\Users\iflyg\.vscode\extensions\ms-python.vscode-pylance-2022.10.30\dist\server.bundle.js:1:422229)
    at _0x4b4eca.<computed>.initialize (c:\Users\iflyg\.vscode\extensions\ms-python.vscode-pylance-2022.10.30\dist\server.bundle.js:1:104221)
    at _0x5327d1.result (c:\Users\iflyg\.vscode\extensions\ms-python.vscode-pylance-2022.10.30\dist\server.bundle.js:1:126358)
    at i (c:\Users\iflyg\.vscode\extensions\ms-python.vscode-pylance-2022.10.30\dist\pyright-internal\src\languageServerBase.ts:1261:19)
    at _0x4a701a.onExecuteCommand (c:\Users\iflyg\.vscode\extensions\ms-python.vscode-pylance-2022.10.30\dist\pyright-internal\src\languageServerBase.ts:1293:13), Error code: ERR_DLOPEN_FAILED
```

intellicode log:
```
Language server is set to Pylance.
Acquiring model
vs-intellicode-python was passed a model: {}.
Acquiring model 'intellisense-members-lstm-pylance' for python
Querying IntelliCode service for available models.
Cached model is up to date.
Activating Python extens
```

**Comment by ayim** [comment]
Hey folks, Pylance has changed a lot since the last time the issue has been reported, could you try the latest version and if it still fails, create a new issue at https://github.com/microsoft/pylance-release?

@erjiaxiao @colorsakura @PrattayDev
