### ISSUE TITLE
Invalid URL on Visual Studio Code Insiders

### ISSUE THREAD

**Issue by heisguyy** [MicrosoftDocs/intellicode#481]
**Product and Version** [VS/VSCode]: Visual Studio Code Insiders
**OS Version** [macOS/Windows]: M1 Mac
**IntelliCode Extension Version**:  v1.2.30
**IntelliCode API Usage Examples**: v0.2.7
**Target Platform or Language** [e.g. Node.js]: Node.js v18.15.0

I am trying to use intellisense in a python script and each time I open it. I get the error about an invalid url.

"""
node:internal/deps/undici/undici:11413
    Error.captureStackTrace(err, this);
          ^

TypeError: Failed to parse URL from /Users/tosin/.vscode-insiders/extensions/visualstudioexptteam.intellicode-api-usage-examples-0.2.7/dist/server/tree-sitter.wasm
    at Object.fetch (node:internal/deps/undici/undici:11413:11)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5) {
  [cause]: TypeError [ERR_INVALID_URL]: Invalid URL
      at new NodeError (node:internal/errors:399:5)
      at URL.onParseError (node:internal/url:566:9)
      at new URL (node:internal/url:646:5)
      at new Request (node:internal/deps/undici/undici:7002:25)
      at fetch2 (node:internal/deps/undici/undici:10554:25)
      at Object.fetch (node:internal/deps/undici/undici:11411:18)
      at fetch (node:internal/process/pre_execution:248:25)
      at /Users/tosin/.vscode-insiders/extensions/visualstudioexptteam.intellicode-api-usage-examples-0.2.7/dist/server/server.js:2:3623815
      at Object.<anonymous> (/Users/tosin/.vscode-insiders/extensions/visualstudioexptteam.intellicode-api-usage-examples-0.2.7/dist/server/server.js:2:3624040)
      at 4087 (/Users/tosin/.vscode-insiders/extensions/visualstudioexptteam.intellicode-api-usage-examples-0.2.7/dist/server/server.js:2:3657710) {
    input: '/Users/tosin/.vscode-insiders/extensions/visualstudioexptteam.intellicode-api-usage-examples-0.2.7/dist/server/tree-sitter.wasm',
    code: 'ERR_INVALID_URL'
  }
}

Node.js v18.15.0
[Info  - 22:47:32] Connection to server got closed. Server will restart.
[Error - 22:47:32] Server initialization failed.
  Message: Pending response rejected since connection got disposed
  Code: -32097 
[Error - 22:47:32] API Usage Examples LSP client: couldn't create connection to server.
  Message: Pending response rejected since connection got disposed
  Code: -32097 
node:internal/deps/undici/undici:11413
    Error.captureStackTrace(err, this);
          ^

TypeError: Failed to parse URL from /Users/tosin/.vscode-insiders/extensions/visualstudioexptteam.intellicode-api-usage-examples-0.2.7/dist/server/tree-sitter.wasm
    at Object.fetch (node:internal/deps/undici/undici:11413:11)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5) {
  [cause]: TypeError [ERR_INVALID_URL]: Invalid URL
      at new NodeError (node:internal/errors:399:5)
      at URL.onParseError (node:internal/url:566:9)
      at new URL (node:internal/url:646:5)
      at new Request (node:internal/deps/undici/undici:7002:25)
      at fetch2 (node:internal/deps/undici/undici:10554:25)
      at Object.fetch (node:internal/deps/undici/undici:11411:18)
      at fetch (node:internal/process/pre_execution:248:25)
      at /Users/tosin/.vscode-insiders/extensions/visualstudioexptteam.intellicode-api-usage-examples-0.2.7/dist/server/server.js:2:3623815
      at Object.<anonymous> (/Users/tosin/.vscode-insiders/extensions/visualstudioexptteam.intellicode-api-usage-examples-0.2.7/dist/server/server.js:2:3624040)
      at 4087 (/Users/tosin/.vscode-insiders/extensions/visualstudioexptteam.intellicode-api-usage-examples-0.2.7/dist/server/server.js:2:3657710) {
    input: '/Users/tosin/.vscode-insiders/extensions/visualstudioexptteam.intellicode-api-usage-examples-0.2.7/dist/server/tree-sitter.wasm',
    code: 'ERR_INVALID_URL'
  }
}

Node.js v18.15.0
[Info  - 22:47:32] Connection to server got closed. Server will restart.
[Error - 22:47:32] Server initialization failed.
  Message: Pending response rejected since connection got disposed
  Code: -32097 
[Error - 22:47:32] API Usage Examples LSP client: couldn't create connection to server.
  Message: Pending response rejected since connection got disposed
  Code: -32097 
node:internal/deps/undici/undici:11413
    Error.captureStackTrace(err, this);
          ^

TypeError: Failed to parse URL from /Users/tosin/.vscode-insiders/extensions/visualstudioexptteam.intellicode-api-usage-examples-0.2.7/dist/server/tree-sitter.wasm
    at Object.fetch (node:internal/deps/undici/undici:11413:11)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5) {
  [cause]: TypeError [ERR_INVALID_URL]: Invalid URL
      at new NodeError (node:internal/errors:399:5)
      at URL.onParseError (node:internal/url:566:9)
      at new URL (node:internal/url:646:5)
      at new Request (node:internal/deps/undici/undici:7002:25)
      at fetch2 (node:internal/deps/undici/undici:10554:25)
      at Object.fetch (node:internal/deps/undici/undici:11411:18)
      at fetch (node:internal/process/pre_execution:248:25)
      at /Users/tosin/.vscode-insiders/extensions/visualstudioexptteam.intellicode-api-usage-examples-0.2.7/dist/server/server.js:2:3623815
      at Object.<anonymous> (/Users/tosin/.vscode-insiders/extensions/visualstudioexptteam.intellicode-api-usage-examples-0.2.7/dist/server/server.js:2:3624040)
      at 4087 (/Users/tosin/.vscode-insiders/extensions/visualstudioexptteam.intellicode-api-usage-examples-0.2.7/dist/server/server.js:2:3657710) {
    input: '/Users/tosin/.vscode-insiders/extensions/visualstudioexptteam.intellicode-api-usage-examples-0.2.7/dist/server/tree-sitter.wasm',
    code: 'ERR_INVALID_URL'
  }
}

Node.js v18.15.0
[Info  - 22:47:33] Connection to server got closed. Server will restart.
[Error - 22:47:33] Server initialization failed.
  Message: Pending response rejected since connection got disposed
  Code: -32097 
[Error - 22:47:33] API Usage Examples LSP client: couldn't create connection to server.
  Message: Pending response rejected since connection got disposed
  Code: -32097 
[Error - 22:47:33] Restarting server failed
  Message: Pending response rejected since connection got disposed
  Code: -32097 
node:internal/deps/undici/undici:11413
    Error.captureStackTrace(err, this);
          ^

TypeError: Failed to parse URL from /Users/tosin/.vscode-insiders/extensions/visualstudioexptteam.intellicode-api-usage-examples-0.2.7/dist/server/tree-sitter.wasm
    at Object.fetch (node:internal/deps/undici/undici:11413:11)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5) {
  [cause]: TypeError [ERR_INVALID_URL]: Invalid URL
      at new NodeError (node:internal/errors:399:5)
      at URL.onParseError (node:internal/url:566:9)
      at new URL (node:internal/url:646:5)
      at new Request (node:internal/deps/undici/undici:7002:25)
      at fetch2 (node:internal/deps/undici/undici:10554:25)
      at Object.fetch (node:internal/deps/undici/undici:11411:18)
      at fetch (node:internal/process/pre_execution:248:25)
      at /Users/tosin/.vscode-insiders/extensions/visualstudioexptteam.intellicode-api-usage-examples-0.2.7/dist/server/server.js:2:3623815
      at Object.<anonymous> (/Users/tosin/.vscode-insiders/extensions/visualstudioexptteam.intellicode-api-usage-examples-0.2.7/dist/server/server.js:2:3624040)
      at 4087 (/Users/tosin/.vscode-insiders/extensions/visualstudioexptteam.intellicode-api-usage-examples-0.2.7/dist/server/server.js:2:3657710) {
    input: '/Users/tosin/.vscode-insiders/extensions/visualstudioexptteam.intellicode-api-usage-examples-0.2.7/dist/server/tree-sitter.wasm',
    code: 'ERR_INVALID_URL'
  }
}

Node.js v18.15.0
[Info  - 22:47:33] Connection to server got closed. Server will restart.
[Error - 22:47:33] Server initialization failed.
  Message: Pending response rejected since connection got disposed
  Code: -32097 
[Error - 22:47:33] API Usage Examples LSP client: couldn't create connection to server.
  Message: Pending response rejected since connection got disposed
  Code: -32097 
[Error - 22:47:33] Restarting server failed
  Message: Pending response rejected since connection got disposed
  Code: -32097 
node:internal/deps/undici/undici:11413
    Error.captureStackTrace(err, this);
          ^

TypeError: Failed to parse URL from /Users/tosin/.vscode-insiders/extensions/visualstudioexptteam.intellicode-api-usage-examples-0.2.7/dist/server/tree-sitter.wasm
    at Object.fetch (node:internal/deps/undici/undici:11413:11)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5) {
  [cause]: TypeError [ERR_INVALID_URL]: Invalid URL
      at new NodeError (node:internal/errors:399:5)
      at URL.onParseError (node:internal/url:566:9)
      at new URL (node:internal/url:646:5)
      at new Request (node:internal/deps/undici/undici:7002:25)
      at fetch2 (node:internal/deps/undici/undici:10554:25)
      at Object.fetch (node:internal/deps/undici/undici:11411:18)
      at fetch (node:internal/process/pre_execution:248:25)
      at /Users/tosin/.vscode-insiders/extensions/visualstudioexptteam.intellicode-api-usage-examples-0.2.7/dist/server/server.js:2:3623815
      at Object.<anonymous> (/Users/tosin/.vscode-insiders/extensions/visualstudioexptteam.intellicode-api-usage-examples-0.2.7/dist/server/server.js:2:3624040)
      at 4087 (/Users/tosin/.vscode-insiders/extensions/visualstudioexptteam.intellicode-api-usage-examples-0.2.7/dist/server/server.js:2:3657710) {
    input: '/Users/tosin/.vscode-insiders/extensions/visualstudioexptteam.intellicode-api-usage-examples-0.2.7/dist/server/tree-sitter.wasm',
    code: 'ERR_INVALID_URL'
  }
}

Node.js v18.15.0
[Error - 22:47:34] The API Usage Examples LSP server crashed 5 times in the last 3 minutes. The server will not be restarted. See the output for more information.
[Error - 22:47:34] Server initialization failed.
  Message: Pending response rejected since connection got disposed
  Code: -32097 
[Error - 22:47:34] API Usage Examples LSP client: couldn't create connection to server.
  Message: Pending response rejected since connection got disposed
  Code: -32097 
[Error - 22:47:34] Restarting server failed
  Message: Pending response rejected since connection got disposed
  Code: -32097 
"""

**Comment by paulwellnerbou** [comment]
Same problem here:

```
node:internal/deps/undici/undici:11413
    Error.captureStackTrace(err, this);
          ^

TypeError: Failed to parse URL from /home/paul/.vscode-insiders/extensions/visualstudioexptteam.intellicode-api-usage-examples-0.2.7/dist/server/tree-sitter.wasm
    at Object.fetch (node:internal/deps/undici/undici:11413:11)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5) {
  [cause]: TypeError [ERR_INVALID_URL]: Invalid URL
      at new NodeError (node:internal/errors:399:5)
      at URL.onParseError (node:internal/url:566:9)
      at new URL (node:internal/url:646:5)
      at new Request (node:internal/deps/undici/undici:7002:25)
      at fetch2 (node:internal/deps/undici/undici:10554:25)
      at Object.fetch (node:internal/deps/undici/undici:11411:18)
      at fetch (node:internal/process/pre_execution:248:25)
      at /home/paul/.vscode-insiders/extensions/visualstudioexptteam.intellicode-api-usage-examples-0.2.7/dist/server/server.js:2:3623815
      at Object.<anonymous> (/home/paul/.vscode-insiders/extensions/visualstudioexptteam.intellicode-api-usage-examples-0.2.7/dist/server/server.js:2:3624040)
      at 4087 (/home/paul/.vscode-insiders/extensions/visualstudioexptteam.intellicode-api-usage-examples-0.2.7/dist/server/server.js:2:3657710) {
    input: '/home/paul/.vscode-insiders/extensions/visualstudioexptteam.intellicode-api-usage-examples-0.2.7/dist/server/tree-sitter.wasm',
    code: 'ERR_INVALID_URL'
  }
}
```

**Comment by julian-poidevin** [comment]
Same issue for me with : - `visualstudioexptteam.vscodeintellicode/extension` : `v1.2.30`
and  the following VSCode config : 
```
Version: 1.82.0-insider
Commit: ad94cf18189746d2e942fda257950901049b3af3
Date: 2023-08-23T05:33:07.513Z
Electron: 25.5.0
ElectronBuildId: 23084831
Chromium: 114.0.5735.289
Node.js: 18.15.0
V8: 11.4.183.29-electron.0
OS: Linux x64 6.1.46-1-lts
```

**Comment by predmaxim** [comment]
Same problem for me 
```
Version: 1.82.0
Release: 23250
Commit: 13ae69686c4390a9aee7b71b44337eb488319f26
Date: 2023-09-07T18:51:47.499Z
Electron: 25.8.0
ElectronBuildId: undefined
Chromium: 114.0.5735.289
Node.js: 18.15.0
V8: 11.4.183.29-electron.0
OS: Linux x64 6.1.49-1-MANJARO
```

````
TypeError: Failed to parse URL from /home/predmaxim/.vscode-oss/extensions/visualstudioexptteam.intellicode-api-usage-examples-0.2.7/dist/server/tree-sitter.wasm
    at Object.fetch (node:internal/deps/undici/undici:11413:11)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5) {
  [cause]: TypeError [ERR_INVALID_URL]: Invalid URL
      at new NodeError (node:internal/errors:399:5)
      at URL.onParseError (node:internal/url:566:9)
      at new URL (node:internal/url:646:5)
      at new Request (node:internal/deps/undici/undici:7002:25)
      at fetch2 (node:internal/deps/undici/undici:10554:25)
      at Object.fetch (node:internal/deps/undici/undici:11411:18)
      at fetch (node:internal/process/pre_execution:237:25)
      at /home/predmaxim/.vscode-oss/extensions/visualstudioexptteam.intellicode-api-usage-examples-0.2.7/dist/server/server.js:2:3623815
      at Object.<anonymous> (/home/predmaxim/.vscode-oss/extensions/visualstudioexptteam.intellicode-api-usage-examples-0.2.7/dist/server/server.js:2:3624040)
      at 4087 (/home/predmaxim/.vscode-oss/extensions/visualstudioexptteam.intellicode-api-usage-examples-0.2.7/dist/server/server.js:2:3657710) {
    input: '/home/predmaxim/.vscode-oss/extensions/visualstudioexptteam.intellicode-api-usage-examples-0.2.7/dist/server/tree-sitter.wasm',
    code: 'ERR_INVALID_URL'
  }
}

Node.js v18.15.0
[Error - 11:06:53] The API Usage Examples LSP server crashed 5 times in the last 3 minutes. The server will not be restarted. See the output for more information.
[Error - 11:06:53] Server initialization failed.
  Message: Pending response rejected since connection got disposed
  Code: -32097 
[Error - 11:06:53] API Usage Examples LSP client: couldn't create connection to server.
  Message: Pending response rejected since connection got disposed
  Code: -32097 
[Error - 11:06:53] Restarting server failed
  Message: Pending response rejected since connection got disposed
  Code: -32097 
```

**Comment by mkmkmk** [comment]
I had the same problem (on not insider VSCode version 1.83, 1.84), I downgraded to 1.81 and now it's OK.
