### ISSUE TITLE
Intelicode for C# Dev Kit Timeout

### ISSUE THREAD

**Issue by patrikpop10** [MicrosoftDocs/intellicode#503]
**Product and Version** [VS/VSCode]: VSCode 182.2
**OS Version** [macOS/Windows]: Windows 11
**IntelliCode Extension Version**: 0.1.26
**Target Platform or Language** [e.g. Node.js]: C#/.NET

There is no code suggestion whenever I try to use the extension.
When checking the logs the following is displayed:

_Error: Operation took longer than 5000ms.
	at Timeout._onTimeout (c:\Users\User\.vscode\extensions\ms-dotnettools.vscodeintellicode-csharp-0.1.26-win32-x64\dist\node_modules\@vsintellicode\completions-csharp\index.js:2:66913)
	at listOnTimeout (node:internal/timers:569:17)
	at process.processTimers (node:internal/timers:512:7)_

Tried using all the other versions of the extension and to use different .NET versions and the issue still persists.

**Comment by Leatensy** [comment]
I have the same issue。
A complete reinstall of vscode won't work either。

**Comment by bradleylandis** [comment]
I have the same issue:

Version: 1.83.1 (user setup)
Commit: f1b07bd25dfad64b0167beb15359ae573aecd2cc
Date: 2023-10-10T23:48:05.904Z
Electron: 25.8.4
ElectronBuildId: 24154031
Chromium: 114.0.5735.289
Node.js: 18.15.0
V8: 11.4.183.29-electron.0
OS: Windows_NT x64 10.0.22621

c# extension: 2.6.24
c# devkit: 0.5.150
intellicode for c# dev kit: 0.1.26

[Completions][1]: [inlineCompletionProvider.provideInlineCompletionItems() 8]  Entered provideInlineCompletionItems() try block
[Completions][1]: [inlineCompletionProvider.provideInlineCompletionItems() 8] Starting request
[Completions][1]: [WorkerLineCompletionService.request() 9]  Entered
[Completions][4]: [inlineCompletionProvider.provideInlineCompletionItems() 8]  Caught error when requesting inline completion: Error: Operation took longer than 5000ms.
[Completions][2]: [inlineCompletionProvider.provideInlineCompletionItems() 8] 
	Wait: 0.16780000925064087ms
	Full inference: 5003.7074999809265
[Completions][4]: [inlineCompletionProvider.provideInlineCompletionItems() 8] Unexpected exception: Operation took longer than 5000ms.
Error: Operation took longer than 5000ms.
	at Timeout._onTimeout (c:\Users\Bradley\.vscode\extensions\ms-dotnettools.vscodeintellicode-csharp-0.1.26-win32-x64\dist\node_modules\@vsintellicode\completions-csharp\index.js:2:66913)
	at listOnTimeout (node:internal/timers:569:17)
	at process.processTimers (node:internal/timers:512:7)

**Comment by qsy1999** [comment]
Same problem for me.

Solved by using VSCode 1.81

**Comment by gmccullo** [comment]
+1. Not on every completion, but on the same stuff consistently. Example:

```
[Completions][2]: [inlineCompletionProvider.provideInlineCompletionItems() 122]  Candidate completion: 
[Completions][2]: [inlineCompletionProvider.provideInlineCompletionItems() 122]  Current line with candidate:

[Completions][1]: [inlineCompletionProvider.provideInlineCompletionItems() 122]  Completion was filtered out because Completion line is an empty string
[Completions][4]: [inlineCompletionProvider.provideInlineCompletionItems() 116]  Caught error when requesting inline completion: Error: Operation took longer than 5000ms.
[Completions][2]: [inlineCompletionProvider.provideInlineCompletionItems() 116] 
	Wait: 0.5313000082969666ms
	Full inference: 5011.440300002694
[Completions][4]: [inlineCompletionProvider.provideInlineCompletionItems() 116] Unexpected exception: Operation took longer than 5000ms.
Error: Operation took longer than 5000ms.
	at Timeout._onTimeout (c:\Users\gary\.vscode\extensions\ms-dotnettools.vscodeintellicode-csharp-0.1.26-win32-x64\dist\node_modules\@vsintellicode\completions-csharp\index.js:2:66913)
	at listOnTimeout (node:internal/timers:569:17)
	at process.processTimers (node:internal/timers:512:7)
```

**Comment by somedeveloper00** [comment]
same issue here. would appreciate it if we could somehow give it more CPU threads to work, or increase the timeout, preferably in standard vscode json settings

**Comment by Einxeld** [comment]
> Same problem for me.
> 
> Solved by using VSCode 1.81

Can confirm uninstalling and installing v1.81 worked for me.

**Comment by somedeveloper00** [comment]
It could also be related to your account not being signed into dev kit. personal accounts dont have permission to sign in, you'll receive a "You can't sign in here with a personal account. Use your work or school account instead." error
