### ISSUE TITLE
Intellicode for Python: 'python.intellicode.loadLanguageServerExtension' not found

### ISSUE THREAD

**Issue by GrigoriOH** [MicrosoftDocs/intellicode#509]
**Product and Version** [VS/VSCode]: VSCodium 1.83.0
**OS Version** [macOS/Windows]: Pop!_OS 22.04 LTS 
**IntelliCode Extension Version**: 1.2.30
**Target Platform or Language** [e.g. Node.js]: Python3

**Steps to Reproduce / Scenario:**

1. Installed intellicode alongside with Pylance (v2023.10.10)
2. Open *.py file
3. Error: "Sorry, something went wrong activating IntelliCode support for Python. Please check the "Python" and "VS IntelliCode" output windows for details."

Log output:
```
Language server is set to Pylance.
Acquiring model
vs-intellicode-python was passed a model: {}.
Acquiring model 'intellisense-members-lstm-pylance' for python
Querying IntelliCode service for available models.
Cached model is up to date.
Activating Python extension
Language server extension command failed. Exception: Error: command 'python.intellicode.loadLanguageServerExtension' not found
    at w._tryExecuteCommand (vscode-file://vscode-app/usr/share/codium/resources/app/out/vs/workbench/workbench.desktop.main.js:1534:16057)
    at w.executeCommand (vscode-file://vscode-app/usr/share/codium/resources/app/out/vs/workbench/workbench.desktop.main.js:1534:15939)
Error while activating Python: {}
```

Some search showed the issue #296, but downgrading to 2021.5.926500501 of the Python extension might not be sensible. Further search lead to https://forum.manjaro.org/t/vscode-intellicode-language-server-error-with-python-with-fix/146447 where downgrading Pylance to v2023.6.40 did the trick.

Testing all Pylance versions beginning with the current one (v2023.10.10) down to v2023.6.40 I was able to reproduce the error with every version except  for v2023.6.40.

Not sure if this issue is properly placed here, or belongs to the Pylance site, also considering I got a fix to use intellicode for my use case, but for further bug fixes and as a resource for persons with the same issue, this might help.

Let me know if there is more data / logs needed to find the cause here.

**Comment by rob4226** [comment]
I am getting the same error messages on Windows 10 when opening a .py file.

```shell
Version: 1.83.0
Release: 23283
Commit: 623395426cc947eec9f40b93b17b0ed45d923b66
Date: 2023-10-10T13:43:30.838Z (1 day ago)
Browser: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) VSCodium/1.83.0 Chrome/114.0.5735.289 Electron/25.8.4 Safari/537.36
```
IntelliCode `v1.2.30`
Python `v2023.18.0`
Pylance `v2023.10.10`

**Comment by ahmedelq** [comment]
Having same issue, have installed both extensions but same error persists.

**Comment by Anton-V-K** [comment]
Downgrading Python extension (`ms-python) from `v2023.20.0` to `v2023.4.1` solved the problem in VSCodium 1.82.0 with Python 3.11.7 on Windows 10 21H1.
Other newer versions of the extension refuse to load properly (because of incompatibility?).

**Comment by advait404** [comment]
I am having the same issue. using latest versions of python, pylance, intellisense and other extenions gives 
"Error: command 'python.intellicode.loadLanguageServerExtension' not found" 

however, downgrading to pylance varsion 2023.6.40 does not give this issue.

**Comment by heamaral** [comment]
Having the same issue here, It seems the issue is present to any version after 2023.6.40.

**Comment by GustavoWidman** [comment]
Same issue using `code` from the arch repo (code-oss). Downgrading Pylance to 2023.6.40 seems to work fine but i'd still rather not run a 1y old version of an extension.

**Comment by kuolemaaa** [comment]
It is INCREDIBLE that after a whole year this is still an issue

Manjaro Linux
code 1.90.0-1
pylance 2024.6.1
intellicode 1.3.1

**Comment by Ywandung-Lyou** [comment]
I met the same problem here. The version of `Pylance` is `v2024.7.1`, and `IntelliCode` `v1.3.1`. Sorry that I cannot show the log here because I was using offline in my company.

**Comment by 21020620** [comment]
Problem persists.
Downgrading Pylance to v2023.6.40 did the trick though.
Just comment to let the devs know the problem still hasn't been fixed yet

**Comment by rkfg** [comment]
Can confirm that Pylance v2023.6.40 is the last working version. Something must have changed on the python side if it only popped up now? I use many Conda environments with 3.10 and 3.11, they're all affected.

**Comment by Nocturnalx** [comment]
It is now October 30th 2024 and switching to v2023.6.40 was still required for me to get it working.

**Comment by oguztecirlioglu** [comment]
The latest version that works for me without breaking things is:
pylance `v2023.6.40` as well - anything after that breaks my IntelliCode.


Kernel: 6.11.2-arch1-1
Code: v1.96.0
Intellicode: 1.3.2

**Comment by jimmy-evo** [comment]
So, just downgrade ?

**Comment by ghost** [comment]
Unfortunately `v2023.6.40` is no longer working as the simply doesn't start up. Insane that this is still an issue.

```
Pylance extension is not activated.
Error while activating Python: {}
```

Python and Pylance are successfully activating despite intellicode's claims:

`2025-02-11 13:28:15.062 [info] Starting Pylance language server.`

Time to ditch code it seems.

**Comment by kuolemaaa** [comment]
just use basedpyright and ruff
