### ISSUE TITLE
Activating intellicode fails with recent Ubuntu update and snap installed VSCode

### ISSUE THREAD

**Issue by dibarbet** [MicrosoftDocs/intellicode#552]
**Product and Version** VSCode 1.88.0
**OS Version** Ubuntu 22.04.4 (though others have the issue):
**IntelliCode Extension Version**: 2.0.25
**Target Platform or Language** [e.g. Node.js]:

**Steps to Reproduce / Scenario:**

On a recently updated version of Ubuntu, using VSCode installed from snap, attempt to open a C# project.  The C# extension will fail to activate with:
```
[Error - 12:31:47 PM] Microsoft.CodeAnalysis.LanguageServer client: couldn't create connection to server.
Error: /snap/core20/current/lib/x86_64-linux-gnu/libc.so.6: version `GLIBC_2.33' not found (required by /lib/x86_64-linux-gnu/libstdc++.so.6)
	at process.func [as dlopen] (node:electron/js2c/node_init:2:2214)
	at Module._extensions..node (node:internal/modules/cjs/loader:1356:18)
	at Object.func [as .node] (node:electron/js2c/node_init:2:2214)
	at Module.load (node:internal/modules/cjs/loader:1126:32)
	at Module._load (node:internal/modules/cjs/loader:967:12)
	at c._load (node:electron/js2c/node_init:2:13672)
	at l._load (/snap/code/156/usr/share/code/resources/app/out/vs/workbench/api/node/extensionHostProcess.js:175:5602)
	at i._load (/snap/code/156/usr/share/code/resources/app/out/vs/workbench/api/node/extensionHostProcess.js:172:29719)
	at t._load (/snap/code/156/usr/share/code/resources/app/out/vs/workbench/api/node/extensionHostProcess.js:137:35279)
	at Module.require (node:internal/modules/cjs/loader:1150:19)
	at h (/snap/code/156/usr/share/code/resources/app/out/vs/loader.js:4:647)
	at Object.<anonymous> (/home/dibarbet/.vscode/extensions/ms-dotnettools.vscodeintellicode-csharp-2.0.25-linux-x64/dist/node_modules/onnxruntime-node/dist/binding.js:9:1)
	at o._compile (/snap/code/156/usr/share/code/resources/app/out/vs/loader.js:4:1271)
	at Module._extensions..js (node:internal/modules/cjs/loader:1326:10)
	at Module.load (node:internal/modules/cjs/loader:1126:32)
	at Module._load (node:internal/modules/cjs/loader:967:12)
	at c._load (node:electron/js2c/node_init:2:13672)
	at l._load (/snap/code/156/usr/share/code/resources/app/out/vs/workbench/api/node/extensionHostProcess.js:175:5602)
	at i._load (/snap/code/156/usr/share/code/resources/app/out/vs/workbench/api/node/extensionHostProcess.js:172:29719)
	at t._load (/snap/code/156/usr/share/code/resources/app/out/vs/workbench/api/node/extensionHostProcess.js:137:35279)
	at Module.require (node:internal/modules/cjs/loader:1150:19)
	at h (/snap/code/156/usr/share/code/resources/app/out/vs/loader.js:4:647)
	at Object.<anonymous> (/home/dibarbet/.vscode/extensions/ms-dotnettools.vscodeintellicode-csharp-2.0.25-linux-x64/dist/node_modules/onnxruntime-node/dist/backend.js:18:19)
	at o._compile (/snap/code/156/usr/share/code/resources/app/out/vs/loader.js:4:1271)
	at Module._extensions..js (node:internal/modules/cjs/loader:1326:10)
	at Module.load (node:internal/modules/cjs/loader:1126:32)
	at Module._load (node:internal/modules/cjs/loader:967:12)
	at c._load (node:electron/js2c/node_init:2:13672)
	at l._load (/snap/code/156/usr/share/code/resources/app/out/vs/workbench/api/node/extensionHostProcess.js:175:5602)
	at i._load (/snap/code/156/usr/share/code/resources/app/out/vs/workbench/api/node/extensionHostProcess.js:172:29719)
	at t._load (/snap/code/156/usr/share/code/resources/app/out/vs/workbench/api/node/extensionHostProcess.js:137:35279)
	at Module.require (node:internal/modules/cjs/loader:1150:19)
	at h (/snap/code/156/usr/share/code/resources/app/out/vs/loader.js:4:647)
	at Object.<anonymous> (/home/dibarbet/.vscode/extensions/ms-dotnettools.vscodeintellicode-csharp-2.0.25-linux-x64/dist/node_modules/onnxruntime-node/dist/index.js:21:17)
	at o._compile (/snap/code/156/usr/share/code/resources/app/out/vs/loader.js:4:1271)
	at Module._extensions..js (node:internal/modules/cjs/loader:1326:10)
	at Module.load (node:internal/modules/cjs/loader:1126:32)
	at Module._load (node:internal/modules/cjs/loader:967:12)
	at c._load (node:electron/js2c/node_init:2:13672)
	at l._load (/snap/code/156/usr/share/code/resources/app/out/vs/workbench/api/node/extensionHostProcess.js:175:5602)
	at i._load (/snap/code/156/usr/share/code/resources/app/out/vs/workbench/api/node/extensionHostProcess.js:172:29719)
	at t._load (/snap/code/156/usr/share/code/resources/app/out/vs/workbench/api/node/extensionHostProcess.js:137:35279)
	at Module.require (node:internal/modules/cjs/loader:1150:19)
	at h (/snap/code/156/usr/share/code/resources/app/out/vs/loader.js:4:647)
	at 884 (/home/dibarbet/.vscode/extensions/ms-dotnettools.vscodeintellicode-csharp-2.0.25-linux-x64/dist/extension.js:2:1301229)
	at __webpack_require__ (/home/dibarbet/.vscode/extensions/ms-dotnettools.vscodeintellicode-csharp-2.0.25-linux-x64/dist/extension.js:2:1449676)
	at 7974 (/home/dibarbet/.vscode/extensions/ms-dotnettools.vscodeintellicode-csharp-2.0.25-linux-x64/dist/extension.js:2:290437)
	at __webpack_require__ (/home/dibarbet/.vscode/extensions/ms-dotnettools.vscodeintellicode-csharp-2.0.25-linux-x64/dist/extension.js:2:1449676)
	at 5175 (/home/dibarbet/.vscode/extensions/ms-dotnettools.vscodeintellicode-csharp-2.0.25-linux-x64/dist/extension.js:2:290103)
	at __webpack_require__ (/home/dibarbet/.vscode/extensions/ms-dotnettools.vscodeintellicode-csharp-2.0.25-linux-x64/dist/extension.js:2:1449676)
	at 3843 (/home/dibarbet/.vscode/extensions/ms-dotnettools.vscodeintellicode-csharp-2.0.25-linux-x64/dist/extension.js:2:323341)
	at __webpack_require__ (/home/dibarbet/.vscode/extensions/ms-dotnettools.vscodeintellicode-csharp-2.0.25-linux-x64/dist/extension.js:2:1449676)
	at 4054 (/home/dibarbet/.vscode/extensions/ms-dotnettools.vscodeintellicode-csharp-2.0.25-linux-x64/dist/extension.js:2:335524)
	at __webpack_require__ (/home/dibarbet/.vscode/extensions/ms-dotnettools.vscodeintellicode-csharp-2.0.25-linux-x64/dist/extension.js:2:1449676)
	at 8746 (/home/dibarbet/.vscode/extensions/ms-dotnettools.vscodeintellicode-csharp-2.0.25-linux-x64/dist/extension.js:2:312316)
	at __webpack_require__ (/home/dibarbet/.vscode/extensions/ms-dotnettools.vscodeintellicode-csharp-2.0.25-linux-x64/dist/extension.js:2:1449676)
	at 9972 (/home/dibarbet/.vscode/extensions/ms-dotnettools.vscodeintellicode-csharp-2.0.25-linux-x64/dist/extension.js:2:1194711)
	at __webpack_require__ (/home/dibarbet/.vscode/extensions/ms-dotnettools.vscodeintellicode-csharp-2.0.25-linux-x64/dist/extension.js:2:1449676)
	at 8902 (/home/dibarbet/.vscode/extensions/ms-dotnettools.vscodeintellicode-csharp-2.0.25-linux-x64/dist/extension.js:2:1196784)
	at __webpack_require__ (/home/dibarbet/.vscode/extensions/ms-dotnettools.vscodeintellicode-csharp-2.0.25-linux-x64/dist/extension.js:2:1449676)
	at /home/dibarbet/.vscode/extensions/ms-dotnettools.vscodeintellicode-csharp-2.0.25-linux-x64/dist/extension.js:2:1450511
	at /home/dibarbet/.vscode/extensions/ms-dotnettools.vscodeintellicode-csharp-2.0.25-linux-x64/dist/extension.js:2:1451450
	at Object.<anonymous> (/home/dibarbet/.vscode/extensions/ms-dotnettools.vscodeintellicode-csharp-2.0.25-linux-x64/dist/extension.js:2:1451489)
	at o._compile (/snap/code/156/usr/share/code/resources/app/out/vs/loader.js:4:1271)
	at Module._extensions..js (node:internal/modules/cjs/loader:1326:10)
	at Module.load (node:internal/modules/cjs/loader:1126:32)
	at Module._load (node:internal/modules/cjs/loader:967:12)
	at c._load (node:electron/js2c/node_init:2:13672)
	at l._load (/snap/code/156/usr/share/code/resources/app/out/vs/workbench/api/node/extensionHostProcess.js:175:5602)
	at i._load (/snap/code/156/usr/share/code/resources/app/out/vs/workbench/api/node/extensionHostProcess.js:172:29719)
	at t._load (/snap/code/156/usr/share/code/resources/app/out/vs/workbench/api/node/extensionHostProcess.js:137:35279)
	at Module.require (node:internal/modules/cjs/loader:1150:19)
	at require (node:internal/modules/cjs/helpers:119:18)
	at Function.i [as __$__nodeRequire] (/snap/code/156/usr/share/code/resources/app/out/vs/loader.js:5:98)
	at m.xb (/snap/code/156/usr/share/code/resources/app/out/vs/workbench/api/node/extensionHostProcess.js:172:30898)
	at async Promise.all (index 0)
```

Disabling the intellicode extension will workaround this issue, as will installing VSCode directly (instead of from snap).

Some notes -
1.  This **only** occurs if VSCode is installed with snap, and if the Ubuntu instance is recently updated (not exactly sure which update).
2.  I'm not 100% certain this is a bug in the intellicode extension.  It may be a bug in the snap version of VSCode - however it only repros against the intellicode extension (and not others).

This was originally reported in https://github.com/dotnet/vscode-csharp/issues/7031

**Comment by vivlimmsft** [comment]
I'm not sure how quickly I'll be able to get to this issue specifically, but this does expose a problem: starred completions and inline completions are currently inextricably linked, but they don't actually depend on each other. So even if inline completions fails to activate in this way, IntelliCode CDK should at least try to provide starred completions. (created #553 about this)

**Comment by olatoft** [comment]
I also have this issue, as mentioned here: https://github.com/dotnet/vscode-csharp/issues/7031#issue-2233080286

I thought I remembered that this issue appeared around the time I updated to VS Code 1.88, so I tried to revert to the 1.87.2 snap, but I had the same issue there.  Maybe I remember incorrectly, maybe some other update around the same time caused the issue.
