### ISSUE TITLE
Couldn't find ms-vsintellicode-typescript

### ISSUE THREAD

**Issue by jjpepper** [MicrosoftDocs/intellicode#565]
<!--

Reporting a Problem
-------------------
I'm not actually seeing any logs in the VS IntelliCode output window, I'm getting the following error in the tsserver.log verbose log file.

```Info 304  [04:39:20.916] Loading global plugin ms-vsintellicode-typescript
Info 305  [04:39:20.916] Enabling plugin ms-vsintellicode-typescript from candidate paths: /home/dev/.vscode-server/extensions/visualstudioexptteam.vscodeintellicode-1.3.1,/home/dev/.vscode-server/extensions/visualstudioexptteam.vscodeintellicode-1.3.1,/vscode/vscode-server/bin/linux-x64/f1e16e1e6214d7c44d078b1f0607b2388f29d729/extensions/node_modules/typescript/lib/typescript.js/../../..
Info 306  [04:39:20.916] Loading ms-vsintellicode-typescript from /home/dev/.vscode-server/extensions/visualstudioexptteam.vscodeintellicode-1.3.1 (resolved to /home/dev/.vscode-server/extensions/visualstudioexptteam.vscodeintellicode-1.3.1/node_modules)
Info 307  [04:39:20.916] Loading ms-vsintellicode-typescript from /home/dev/.vscode-server/extensions/visualstudioexptteam.vscodeintellicode-1.3.1 (resolved to /home/dev/.vscode-server/extensions/visualstudioexptteam.vscodeintellicode-1.3.1/node_modules)
Info 308  [04:39:20.916] Loading ms-vsintellicode-typescript from /vscode/vscode-server/bin/linux-x64/f1e16e1e6214d7c44d078b1f0607b2388f29d729/extensions/node_modules/typescript/lib/typescript.js/../../.. (resolved to /vscode/vscode-server/bin/linux-x64/f1e16e1e6214d7c44d078b1f0607b2388f29d729/extensions/node_modules/node_modules)
Info 309  [04:39:20.917] Failed to load module 'ms-vsintellicode-typescript' from /home/dev/.vscode-server/extensions/visualstudioexptteam.vscodeintellicode-1.3.1/node_modules: Error: Could not resolve JS module 'ms-vsintellicode-typescript' starting at '/home/dev/.vscode-server/extensions/visualstudioexptteam.vscodeintellicode-1.3.1/node_modules'. Looked in: /home/dev/.vscode-server/extensions/visualstudioexptteam.vscodeintellicode-1.3.1/node_modules/ms-vsintellicode-typescript/package.json, /home/dev/.vscode-server/extensions/visualstudioexptteam.vscodeintellicode-1.3.1/node_modules/ms-vsintellicode-typescript.js, /home/dev/.vscode-server/extensions/visualstudioexptteam.vscodeintellicode-1.3.1/node_modules/ms-vsintellicode-typescript.jsx, /home/dev/.vscode-server/extensions/visualstudioexptteam.vscodeintellicode-1.3.1/node_modules/ms-vsintellicode-typescript/index.js, /home/dev/.vscode-server/extensions/visualstudioexptteam.vscodeintellicode-1.3.1/node_modules/ms-vsintellicode-typescript/index.jsx, /home/dev/.vscode-server/extensions/node_modules/ms-vsintellicode-typescript/package.json, /home/dev/.vscode-server/extensions/node_modules/ms-vsintellicode-typescript.js, /home/dev/.vscode-server/extensions/node_modules/ms-vsintellicode-typescript.jsx, /home/dev/.vscode-server/extensions/node_modules/ms-vsintellicode-typescript/index.js, /home/dev/.vscode-server/extensions/node_modules/ms-vsintellicode-typescript/index.jsx, /home/dev/.vscode-server/node_modules/ms-vsintellicode-typescript/package.json, /home/dev/.vscode-server/node_modules/ms-vsintellicode-typescript.js, /home/dev/.vscode-server/node_modules/ms-vsintellicode-typescript.jsx, /home/dev/.vscode-server/node_modules/ms-vsintellicode-typescript/index.js, /home/dev/.vscode-server/node_modules/ms-vsintellicode-typescript/index.jsx, /home/dev/node_modules/ms-vsintellicode-typescript/package.json, /home/dev/node_modules/ms-vsintellicode-typescript.js, /home/dev/node_modules/ms-vsintellicode-typescript.jsx, /home/dev/node_modules/ms-vsintellicode-typescript/index.js, /home/dev/node_modules/ms-vsintellicode-typescript/index.jsx, /home/node_modules/ms-vsintellicode-typescript/package.json, /home/node_modules/ms-vsintellicode-typescript.js, /home/node_modules/ms-vsintellicode-typescript.jsx, /home/node_modules/ms-vsintellicode-typescript/index.js, /home/node_modules/ms-vsintellicode-typescript/index.jsx, /node_modules/ms-vsintellicode-typescript/package.json, /node_modules/ms-vsintellicode-typescript.js, /node_modules/ms-vsintellicode-typescript.jsx, /node_modules/ms-vsintellicode-typescript/index.js, /node_modules/ms-vsintellicode-typescript/index.jsx
    at resolveJSModule (/vscode/vscode-server/bin/linux-x64/f1e16e1e6214d7c44d078b1f0607b2388f29d729/extensions/node_modules/typescript/lib/typescript.js:44094:11)
    at Object.require (/vscode/vscode-server/bin/linux-x64/f1e16e1e6214d7c44d078b1f0607b2388f29d729/extensions/node_modules/typescript/lib/typescript.js:8542:30)
    at _Project.importServicePluginSync (/vscode/vscode-server/bin/linux-x64/f1e16e1e6214d7c44d078b1f0607b2388f29d729/extensions/node_modules/typescript/lib/typescript.js:182283:27)
    at _ProjectService.requestEnablePlugin (/vscode/vscode-server/bin/linux-x64/f1e16e1e6214d7c44d078b1f0607b2388f29d729/extensions/node_modules/typescript/lib/typescript.js:187834:16)
    at ConfiguredProject2.enablePlugin (/vscode/vscode-server/bin/linux-x64/f1e16e1e6214d7c44d078b1f0607b2388f29d729/extensions/node_modules/typescript/lib/typescript.js:183593:25)
    at ConfiguredProject2.enableGlobalPlugins (/vscode/vscode-server/bin/linux-x64/f1e16e1e6214d7c44d078b1f0607b2388f29d729/extensions/node_modules/typescript/lib/typescript.js:183589:12)
    at ConfiguredProject2.enablePluginsWithOptions (/vscode/vscode-server/bin/linux-x64/f1e16e1e6214d7c44d078b1f0607b2388f29d729/extensions/node_modules/typescript/lib/typescript.js:184357:17)
    at _ProjectService.loadConfiguredProject (/vscode/vscode-server/bin/linux-x64/f1e16e1e6214d7c44d078b1f0607b2388f29d729/extensions/node_modules/typescript/lib/typescript.js:186133:13)
    at _ProjectService.reloadConfiguredProject (/vscode/vscode-server/bin/linux-x64/f1e16e1e6214d7c44d078b1f0607b2388f29d729/extensions/node_modules/typescript/lib/typescript.js:186385:10)
    at ConfiguredProject2.updateGraph (/vscode/vscode-server/bin/linux-x64/f1e16e1e6214d7c44d078b1f0607b2388f29d729/extensions/node_modules/typescript/lib/typescript.js:184283:29)
    at updateWithTriggerFile (/vscode/vscode-server/bin/linux-x64/f1e16e1e6214d7c44d078b1f0607b2388f29d729/extensions/node_modules/typescript/lib/typescript.js:184770:11)
    at updateConfiguredProject (/vscode/vscode-server/bin/linux-x64/f1e16e1e6214d7c44d078b1f0607b2388f29d729/extensions/node_modules/typescript/lib/typescript.js:184778:9)
    at _ProjectService.findCreateOrReloadConfiguredProject (/vscode/vscode-server/bin/linux-x64/f1e16e1e6214d7c44d078b1f0607b2388f29d729/extensions/node_modules/typescript/lib/typescript.js:187247:44)
    at _ProjectService.tryFindDefaultConfiguredProjectForOpenScriptInfo (/vscode/vscode-server/bin/linux-x64/f1e16e1e6214d7c44d078b1f0607b2388f29d729/extensions/node_modules/typescript/lib/typescript.js:187271:25)
    at _ProjectService.tryFindDefaultConfiguredProjectAndLoadAncestorsForOpenScriptInfo (/vscode/vscode-server/bin/linux-x64/f1e16e1e6214d7c44d078b1f0607b2388f29d729/extensions/node_modules/typescript/lib/typescript.js:187317:25)
    at _ProjectService.assignProjectToOpenedScriptInfo (/vscode/vscode-server/bin/linux-x64/f1e16e1e6214d7c44d078b1f0607b2388f29d729/extensions/node_modules/typescript/lib/typescript.js:187202:27)
    at /vscode/vscode-server/bin/linux-x64/f1e16e1e6214d7c44d078b1f0607b2388f29d729/extensions/node_modules/typescript/lib/typescript.js:187575:25
    at Array.forEach (<anonymous>)
    at _ProjectService.applyChangesInOpenFiles (/vscode/vscode-server/bin/linux-x64/f1e16e1e6214d7c44d078b1f0607b2388f29d729/extensions/node_modules/typescript/lib/typescript.js:187573:56)
    at updateOpen (/vscode/vscode-server/bin/linux-x64/f1e16e1e6214d7c44d078b1f0607b2388f29d729/extensions/node_modules/typescript/lib/typescript.js:188764:29)
    at /vscode/vscode-server/bin/linux-x64/f1e16e1e6214d7c44d078b1f0607b2388f29d729/extensions/node_modules/typescript/lib/typescript.js:191397:69
    at IpcIOSession.executeWithRequestId (/vscode/vscode-server/bin/linux-x64/f1e16e1e6214d7c44d078b1f0607b2388f29d729/extensions/node_modules/typescript/lib/typescript.js:191389:14)
    at IpcIOSession.executeCommand (/vscode/vscode-server/bin/linux-x64/f1e16e1e6214d7c44d078b1f0607b2388f29d729/extensions/node_modules/typescript/lib/typescript.js:191397:29)
    at IpcIOSession.onMessage (/vscode/vscode-server/bin/linux-x64/f1e16e1e6214d7c44d078b1f0607b2388f29d729/extensions/node_modules/typescript/lib/typescript.js:191439:51)
    at process.<anonymous> (/vscode/vscode-server/bin/linux-x64/f1e16e1e6214d7c44d078b1f0607b2388f29d729/extensions/node_modules/typescript/lib/tsserver.js:523:14)
    at process.emit (node:events:518:28)
    at emit (node:internal/child_process:951:14)
    at process.processTicksAndRejections (node:internal/process/task_queues:83:21)
```

I was told to raise this with you by the vscode team [here](https://github.com/microsoft/vscode/issues/196528).

**Steps to Reproduce / Scenario:**

1.  Unsure

**Comment by jjpepper** [comment]
how long does it typically take for someone to take a look at an issue like this?  It's a really frustrating problem that I'd love to get to the bottom of.  I have tried boosting memory for typescript server as follows:

`"typescript.tsserver.maxTsServerMemory": 3572`

**Comment by luis-agm** [comment]
I've been dealing with this for a few weeks already, with that same message in the logs, and upping the max memory to `4096` worked a bit. It doesn't crash anymore although some times it takes a long time to load, e.g hovering over a variable stays as 'loading...' for a long time. Still have to reload vscode every now and then when it gets stuck like that, but no useful logs so far. I'll add the logs here if I manage to catch anything useful.

For some context, I do work in a very large monorepo, I only have 16gb of memory and webpack/rspack alone takes 10gb so the macbook is usually swapping around 12gb.

**Comment by jjpepper** [comment]
ok thanks.  I'm using a dev container with a whole bunch of small repos
mounted inside, so the workspace is big

**Comment by marco-quintella** [comment]
Same here. Had to turn off Intllicode extension to be able to use TS Server.

**Comment by Nick2bad4u** [comment]
Same issue here, although my issue is a bit weirder as my Typescript server will start, but restarting it from inside VSCode gives you the error above.

Ill attach full debug logs to see if it can give you the info to track it down.

VSCode logs:
```logs
2025-06-26 13:58:07.094 [info] Killing TS Server
2025-06-26 13:58:07.094 [info] Starting TS Server
2025-06-26 13:58:07.094 [info] Using tsserver from: c:\Users\Nick\Dropbox\PC (2)\Documents\GitHub\Uptime-Watcher\node_modules\typescript\lib\tsserver.js
2025-06-26 13:58:07.094 [info] Using Node installation from C:\Program Files\nodejs\node.exe to run TS Server
2025-06-26 13:58:07.094 [info] <syntax> Log file: c:\Users\Nick\AppData\Roaming\Code\logs\20250626T134302\window1\exthost\vscode.typescript-language-features\tsserver-log-xk9dl6\tsserver.log
2025-06-26 13:58:07.094 [info] <syntax> Trace directory: c:\Users\Nick\AppData\Roaming\Code\logs\20250626T134302\window1\exthost\vscode.typescript-language-features\tsserver-log-6VVfeT
2025-06-26 13:58:07.094 [info] <syntax> Forking...
2025-06-26 13:58:07.095 [info] <syntax> Starting...
2025-06-26 13:58:07.095 [info] <diagnostics> Log file: c:\Users\Nick\AppData\Roaming\Code\logs\20250626T134302\window1\exthost\vscode.typescript-language-features\tsserver-log-09Qisa\tsserver.log
2025-06-26 13:58:07.095 [info] <diagnostics> Trace directory: c:\Users\Nick\AppData\Roaming\Code\logs\20250626T134302\window1\exthost\vscode.typescript-language-features\tsserver-log-766kNU
2025-06-26 13:58:07.095 [info] <diagnostics> Forking...
2025-06-26 13:58:07.095 [info] <diagnostics> Starting...
2025-06-26 13:58:07.095 [error] TSServer exited. Code: null. Signal: SIGTERM
```

Diagnostics Log Files:

[tsserver.log](https://github.com/user-attachments/files/20931062/tsserver.log)

[trace.34060.json](https://github.com/user-attachments/files/20931064/trace.34060.json)

Semantic Log Files:

[tsserver.log](https://github.com/user-attachments/files/20931076/tsserver.log)

[trace.15900.json](https://github.com/user-attachments/files/20931069/trace.15900.json)

Syntax Log Files:

[tsserver.log](https://github.com/user-attachments/files/20931231/tsserver.log)

[trace.50668.json](https://github.com/user-attachments/files/20931235/trace.50668.json)

Generic TypeScript.log from root of ``window1\exthost\vscode.typescript-language-features``

[TypeScript.log](https://github.com/user-attachments/files/20931093/TypeScript.log)

Full exthost Log output (Zipped):

[exthost.zip](https://github.com/user-attachments/files/20931127/exthost.zip)

Thats about all the data/logging I can think to grab for you.

One thing that's kind of funny, is if I switch to the [Native Preview](https://marketplace.visualstudio.com/items?itemName=TypeScriptTeam.native-preview), it works fine.

**Comment by TheDirigible** [comment]
# VS Code IntelliCode Restart Loop — Fixed
**Symptom:**  
`tsserver` restarted endlessly with errors like
```
Failed to load module 'ms-vsintellicode-typescript'
```
even though IntelliCode appeared installed and TypeScript linting still worked.

**Effect:** As long as vscode is running: CPU load, memory ballooning, disk and wsl churn, UI degradation, background tasks delayed
**View:** echo '' > /tmp/tsserver.log && export TSS_LOG="-level normal -file /tmp/tsserver.log" && code . && tail -f /tmp/tsserver.log | ff -i failed.to.load
### Root Cause
Microsoft doesn't bother testing or fixing things for years, even when they are tiny fixes, and causing major problems.
The IntelliCode extension (`visualstudioexptteam.vscodeintellicode`) version **1.3.2** still listed two TypeScript plugins:
- `@vsintellicode/typescript-intellicode-plugin` — exists and works
- `ms-vsintellicode-typescript` — obsolete, missing from the extension bundle
VS Code cached this plugin list in its remote data folder (`~/.vscode-server/data/User/...`).  
Each time `tsserver` tried to load the missing plugin, it crashed and restarted.
### Fix Steps
1. **Close VSCode**
    And maybe restart WSL
2. **Edit the IntelliCode manifest**
    ```bash
    vi ~/.vscode-server/extensions/visualstudioexptteam.vscodeintellicode-1.3.2/package.json
    ```
     Remove the old plugin entry for ms-vsintellicode-typescript so it just looks like:
    ```json
    "typescriptServerPlugins": [
        {
            "name": "@vsintellicode/typescript-intellicode-plugin",
            "languages": [],
            "enableForWorkspaceTypeScriptVersions": true
        }
    ]
    ```
3. **Clear VS Code’s remote caches**
    ```bash
    pkill -f vscode-server
    rm -rf ~/.vscode-server/data/User/workspaceStorage
    rm -rf ~/.vscode-server/data/User/globalStorage/ms-vscode.vscode-typescript-next*
    rm -rf ~/.vscode-server/data/logs
    ```
4. **Reopen the workspace in VS Code (WSL)**  
VS Code now reloads IntelliCode’s correct manifest and starts `tsserver` cleanly.

# More WSL fixes
Default WSL has a lot of problems, I recommend talking to AI if you keep running out of memory.
- completely remove snap - warning, it can hose configs like .ssh/config
- stop infinite logging - edit /etc/systemd/journald.conf
- optional: Disable unneeded services:
    sudo systemctl disable --now rsyslog cron atd unattended-upgrades
    sudo apt purge unattended-upgrades rsyslog
- optional: Remove GUI bloat: 
    sudo apt purge snapd gnome-software apport whoopsie
- optional: Faster DNS: change /etc/resolv.conf to use 1.1.1.1, also set generateResolvConf = false
- optional: Exclude from virus scans: Settings → Virus & threat protection → Manage settings → Add exclusion → \\wsl$

# System slowdown and periodic freezing for 20-30 seconds 
Despite low cpu load and memory usage.
Happens with WSL+vscode / nvidia / especially on Lenovo machines
**Cause:** runaway ETW (Event Tracing for Windows) loggers, mainly Admin_PS_Provider, NVIDIA-NVTOPPS-FILTER, LenovoVantageService, and LwtNetLog keep writing millions of trace buffers even when idle.
**Effect:** kernel ETW pool filled up, stalling I/O and freezing the system.
**Fix:** stop those loggers, disable their auto-start registry entries, and cap them to **10 MB circular logs** so they can’t grow or respawn.
To view the main offenders you need to install Windows Performance Toolkit (minimal is still 600mb, ugh), then run Powershell as admin:
```bash
xperf -loggers | ForEach-Object -Begin { $name = "" } -Process {
if($_ -match "^Logger Name\s+:\s+(.+)$"){ $name = $matches[1] }
elseif($_ -match "Buffers Written\s+:\s+(\d+)"){ [PSCustomObject]@{ Name=$name; BuffersWritten=[int]$matches[1] } }
} | Sort-Object BuffersWritten -Descending | Select-Object -First 15
```
There was more, but I forget it all. I lived with this crap for years. But now I can use VSCode without rebooting every few hours. Vote to end monopolies.

**Comment by Nick2bad4u** [comment]
> # VS Code IntelliCode Restart Loop — Fixed
> **Symptom:**  
> `tsserver` restarted endlessly with errors like
> ```
> Failed to load module 'ms-vsintellicode-typescript'
> ```
> even though IntelliCode appeared installed and TypeScript linting still worked.
> 
> **Effect:** As long as vscode is running: CPU load, memory ballooning, disk and wsl churn, UI degradation, background tasks delayed
> **View:** echo '' > /tmp/tsserver.log && export TSS_LOG="-level normal -file /tmp/tsserver.log" && code . && tail -f /tmp/tsserver.log | ff -i failed.to.load
> ### Root Cause
> Microsoft doesn't bother testing or fixing things for years, even when they are tiny fixes, and causing major problems.
> The IntelliCode extension (`visualstudioexptteam.vscodeintellicode`) version **1.3.2** still listed two TypeScript plugins:
> - `@vsintellicode/typescript-intellicode-plugin` — exists and works
> - `ms-vsintellicode-typescript` — obsolete, missing from the extension bundle
> VS Code cached this plugin list in its remote data folder (`~/.vscode-server/data/User/...`).  
> Each time `tsserver` tried to load the missing plugin, it crashed and restarted.
> ### Fix Steps
> 1. **Close VSCode**
>     And maybe restart WSL
> 2. **Edit the IntelliCode manifest**
>     ```bash
>     vi ~/.vscode-server/extensions/visualstudioexptteam.vscodeintellicode-1.3.2/package.json
>     ```
>      Remove the old plugin entry for ms-vsintellicode-typescript so it just looks like:
>     ```json
>     "typescriptServerPlugins": [
>         {
>             "name": "@vsintellicode/typescript-intellicode-plugin",
>             "languages": [],
>             "enableForWorkspaceTypeScriptVersions": true
>         }
>     ]
>     ```
> 3. **Clear VS Code’s remote caches**
>     ```bash
>     pkill -f vscode-server
>     rm -rf ~/.vscode-server/data/User/workspaceStorage
>     rm -rf ~/.vscode-server/data/User/globalStorage/ms-vscode.vscode-typescript-next*
>     rm -rf ~/.vscode-server/data/logs
>     ```
> 4. **Reopen the workspace in VS Code (WSL)**  
> VS Code now reloads IntelliCode’s correct manifest and starts `tsserver` cleanly.
> 
> # More WSL fixes
> Default WSL has a lot of problems, I recommend talking to AI if you keep running out of memory.
> - completely remove snap - warning, it can hose configs like .ssh/config
> - stop infinite logging - edit /etc/systemd/journald.conf
> - optional: Disable unneeded services:
>     sudo systemctl disable --now rsyslog cron atd unattended-upgrades
>     sudo apt purge unattended-upgrades rsyslog
> - optional: Remove GUI bloat: 
>     sudo apt purge snapd gnome-software apport whoopsie
> - optional: Faster DNS: change /etc/resolv.conf to use 1.1.1.1, also set generateResolvConf = false
> - optional: Exclude from virus scans: Settings → Virus & threat protection → Manage settings → Add exclusion → \\wsl$
> 
> # System slowdown and periodic freezing for 20-30 seconds 
> Despite low cpu load and memory usage.
> Happens with WSL+vscode / nvidia / especially on Lenovo machines
> **Cause:** runaway ETW (Event Tracing for Windows) loggers, mainly Admin_PS_Provider, NVIDIA-NVTOPPS-FILTER, LenovoVantageService, and LwtNetLog keep writing millions of trace buffers even when idle.
> **Effect:** kernel ETW pool filled up, stalling I/O and freezing the system.
> **Fix:** stop those loggers, disable their auto-start registry entries, and cap them to **10 MB circular logs** so they can’t grow or respawn.
> To view the main offenders you need to install Windows Performance Toolkit (minimal is still 600mb, ugh), then run Powershell as admin:
> ```bash
> xperf -loggers | ForEach-Object -Begin { $name = "" } -Process {
> if($_ -match "^Logger Name\s+:\s+(.+)$"){ $name = $matches[1] }
> elseif($_ -match "Buffers Written\s+:\s+(\d+)"){ [PSCustomObject]@{ Name=$name; BuffersWritten=[int]$matches[1] } }
> } | Sort-Object BuffersWritten -Descending | Select-Object -First 15
> ```
> There was more, but I forget it all. I lived with this crap for years. But now I can use VSCode without rebooting every few hours. Vote to end monopolies.

Is this a fix for windows or only wsl environments?
