### ISSUE TITLE
IntelliCode not working

### ISSUE THREAD

**Issue by MichaelViera** [MicrosoftDocs/intellicode#584]
Type: <b>Bug</b>

IntelliCode features will not be available, ms-dotnettools.vscodeintellicode-csharp failed to activate.

**OUTPUT:**

Using dotnet configured on PATH
Dotnet path: C:\Program Files\dotnet\dotnet.exe
Activating C# + C# Dev Kit + C# IntelliCode...
Activation of ms-dotnettools.vscodeintellicode-csharp failed
Activating extension 'ms-dotnettools.vscodeintellicode-csharp' failed: The specified module could not be found.
\\?\c:\Users\micha\.vscode\extensions\ms-dotnettools.vscodeintellicode-csharp-2.1.11-win32-x64\dist\node_modules\onnxruntime-node\bin\napi-v3\win32\x64\onnxruntime_binding.node.
Error: The specified module could not be found.
\\?\c:\Users\micha\.vscode\extensions\ms-dotnettools.vscodeintellicode-csharp-2.1.11-win32-x64\dist\node_modules\onnxruntime-node\bin\napi-v3\win32\x64\onnxruntime_binding.node
	at process.func [as dlopen] (node:electron/js2c/node_init:2:2559)
	at Module._extensions..node (node:internal/modules/cjs/loader:1602:18)
	at Object.func [as .node] (node:electron/js2c/node_init:2:2559)
	at Module.load (node:internal/modules/cjs/loader:1295:32)
	at Module._load (node:internal/modules/cjs/loader:1111:12)
	at c._load (node:electron/js2c/node_init:2:16955)
	at e._load (file:///c:/Users/micha/AppData/Local/Programs/Microsoft%20VS%20Code/resources/app/out/vs/workbench/api/node/extensionHostProcess.js:174:10879)
	at t._load (file:///c:/Users/micha/AppData/Local/Programs/Microsoft%20VS%20Code/resources/app/out/vs/workbench/api/node/extensionHostProcess.js:166:22433)
	at i._load (file:///c:/Users/micha/AppData/Local/Programs/Microsoft%20VS%20Code/resources/app/out/vs/workbench/api/node/extensionHostProcess.js:158:4651)
	at Module.require (node:internal/modules/cjs/loader:1318:19)
	at require (node:internal/modules/helpers:179:18)
	at Object.<anonymous> (c:\Users\micha\.vscode\extensions\ms-dotnettools.vscodeintellicode-csharp-2.1.11-win32-x64\dist\node_modules\onnxruntime-node\dist\binding.js:9:1)
	at Module._compile (node:internal/modules/cjs/loader:1484:14)
	at Module._extensions..js (node:internal/modules/cjs/loader:1564:10)
	at Module.load (node:internal/modules/cjs/loader:1295:32)
	at Module._load (node:internal/modules/cjs/loader:1111:12)
	at c._load (node:electron/js2c/node_init:2:16955)
	at e._load (file:///c:/Users/micha/AppData/Local/Programs/Microsoft%20VS%20Code/resources/app/out/vs/workbench/api/node/extensionHostProcess.js:174:10879)
	at t._load (file:///c:/Users/micha/AppData/Local/Programs/Microsoft%20VS%20Code/resources/app/out/vs/workbench/api/node/extensionHostProcess.js:166:22433)
	at i._load (file:///c:/Users/micha/AppData/Local/Programs/Microsoft%20VS%20Code/resources/app/out/vs/workbench/api/node/extensionHostProcess.js:158:4651)
	at Module.require (node:internal/modules/cjs/loader:1318:19)
	at require (node:internal/modules/helpers:179:18)
	at Object.<anonymous> (c:\Users\micha\.vscode\extensions\ms-dotnettools.vscodeintellicode-csharp-2.1.11-win32-x64\dist\node_modules\onnxruntime-node\dist\backend.js:18:19)
	at Module._compile (node:internal/modules/cjs/loader:1484:14)
	at Module._extensions..js (node:internal/modules/cjs/loader:1564:10)
	at Module.load (node:internal/modules/cjs/loader:1295:32)
	at Module._load (node:internal/modules/cjs/loader:1111:12)
	at c._load (node:electron/js2c/node_init:2:16955)
	at e._load (file:///c:/Users/micha/AppData/Local/Programs/Microsoft%20VS%20Code/resources/app/out/vs/workbench/api/node/extensionHostProcess.js:174:10879)
	at t._load (file:///c:/Users/micha/AppData/Local/Programs/Microsoft%20VS%20Code/resources/app/out/vs/workbench/api/node/extensionHostProcess.js:166:22433)
	at i._load (file:///c:/Users/micha/AppData/Local/Programs/Microsoft%20VS%20Code/resources/app/out/vs/workbench/api/node/extensionHostProcess.js:158:4651)
	at Module.require (node:internal/modules/cjs/loader:1318:19)
	at require (node:internal/modules/helpers:179:18)
	at Object.<anonymous> (c:\Users\micha\.vscode\extensions\ms-dotnettools.vscodeintellicode-csharp-2.1.11-win32-x64\dist\node_modules\onnxruntime-node\dist\index.js:21:17)
	at Module._compile (node:internal/modules/cjs/loader:1484:14)
	at Module._extensions..js (node:internal/modules/cjs/loader:1564:10)
	at Module.load (node:internal/modules/cjs/loader:1295:32)
	at Module._load (node:internal/modules/cjs/loader:1111:12)
	at c._load (node:electron/js2c/node_init:2:16955)
	at e._load (file:///c:/Users/micha/AppData/Local/Programs/Microsoft%20VS%20Code/resources/app/out/vs/workbench/api/node/extensionHostProcess.js:174:10879)
	at t._load (file:///c:/Users/micha/AppData/Local/Programs/Microsoft%20VS%20Code/resources/app/out/vs/workbench/api/node/extensionHostProcess.js:166:22433)
	at i._load (file:///c:/Users/micha/AppData/Local/Programs/Microsoft%20VS%20Code/resources/app/out/vs/workbench/api/node/extensionHostProcess.js:158:4651)
	at Module.require (node:internal/modules/cjs/loader:1318:19)
	at require (node:internal/modules/helpers:179:18)
	at 90884 (c:\Users\micha\.vscode\extensions\ms-dotnettools.vscodeintellicode-csharp-2.1.11-win32-x64\dist\extension.js:2:1529330)
	at __webpack_require__ (c:\Users\micha\.vscode\extensions\ms-dotnettools.vscodeintellicode-csharp-2.1.11-win32-x64\dist\extension.js:2:1677810)
	at 67974 (c:\Users\micha\.vscode\extensions\ms-dotnettools.vscodeintellicode-csharp-2.1.11-win32-x64\dist\extension.js:2:337999)
	at __webpack_require__ (c:\Users\micha\.vscode\extensions\ms-dotnettools.vscodeintellicode-csharp-2.1.11-win32-x64\dist\extension.js:2:1677810)
	at 95175 (c:\Users\micha\.vscode\extensions\ms-dotnettools.vscodeintellicode-csharp-2.1.11-win32-x64\dist\extension.js:2:337662)
	at __webpack_require__ (c:\Users\micha\.vscode\extensions\ms-dotnettools.vscodeintellicode-csharp-2.1.11-win32-x64\dist\extension.js:2:1677810)
	at 23843 (c:\Users\micha\.vscode\extensions\ms-dotnettools.vscodeintellicode-csharp-2.1.11-win32-x64\dist\extension.js:2:370955)
	at __webpack_require__ (c:\Users\micha\.vscode\extensions\ms-dotnettools.vscodeintellicode-csharp-2.1.11-win32-x64\dist\extension.js:2:1677810)
	at 84054 (c:\Users\micha\.vscode\extensions\ms-dotnettools.vscodeintellicode-csharp-2.1.11-win32-x64\dist\extension.js:2:383169)
	at __webpack_require__ (c:\Users\micha\.vscode\extensions\ms-dotnettools.vscodeintellicode-csharp-2.1.11-win32-x64\dist\extension.js:2:1677810)
	at 38746 (c:\Users\micha\.vscode\extensions\ms-dotnettools.vscodeintellicode-csharp-2.1.11-win32-x64\dist\extension.js:2:359907)
	at __webpack_require__ (c:\Users\micha\.vscode\extensions\ms-dotnettools.vscodeintellicode-csharp-2.1.11-win32-x64\dist\extension.js:2:1677810)
	at 69972 (c:\Users\micha\.vscode\extensions\ms-dotnettools.vscodeintellicode-csharp-2.1.11-win32-x64\dist\extension.js:2:1364345)
	at __webpack_require__ (c:\Users\micha\.vscode\extensions\ms-dotnettools.vscodeintellicode-csharp-2.1.11-win32-x64\dist\extension.js:2:1677810)
	at 98902 (c:\Users\micha\.vscode\extensions\ms-dotnettools.vscodeintellicode-csharp-2.1.11-win32-x64\dist\extension.js:2:1366539)
	at __webpack_require__ (c:\Users\micha\.vscode\extensions\ms-dotnettools.vscodeintellicode-csharp-2.1.11-win32-x64\dist\extension.js:2:1677810)
	at c:\Users\micha\.vscode\extensions\ms-dotnettools.vscodeintellicode-csharp-2.1.11-win32-x64\dist\extension.js:2:1678646
	at c:\Users\micha\.vscode\extensions\ms-dotnettools.vscodeintellicode-csharp-2.1.11-win32-x64\dist\extension.js:2:1681650
	at Object.<anonymous> (c:\Users\micha\.vscode\extensions\ms-dotnettools.vscodeintellicode-csharp-2.1.11-win32-x64\dist\extension.js:2:1681689)
	at Module._compile (node:internal/modules/cjs/loader:1484:14)
	at Module._extensions..js (node:internal/modules/cjs/loader:1564:10)
	at Module.load (node:internal/modules/cjs/loader:1295:32)
	at Module._load (node:internal/modules/cjs/loader:1111:12)
	at c._load (node:electron/js2c/node_init:2:16955)
	at e._load (file:///c:/Users/micha/AppData/Local/Programs/Microsoft%20VS%20Code/resources/app/out/vs/workbench/api/node/extensionHostProcess.js:174:10879)
	at t._load (file:///c:/Users/micha/AppData/Local/Programs/Microsoft%20VS%20Code/resources/app/out/vs/workbench/api/node/extensionHostProcess.js:166:22433)
	at i._load (file:///c:/Users/micha/AppData/Local/Programs/Microsoft%20VS%20Code/resources/app/out/vs/workbench/api/node/extensionHostProcess.js:158:4651)
	at Module.require (node:internal/modules/cjs/loader:1318:19)
	at require (node:internal/modules/helpers:179:18)
	at z_.xb (file:///c:/Users/micha/AppData/Local/Programs/Microsoft%20VS%20Code/resources/app/out/vs/workbench/api/node/extensionHostProcess.js:166:23753)
	at async Promise.all (index 0)
waiting for named pipe information from server...
[stdout] {"pipeName":"\\\\.\\pipe\\8d5fcaaf"}
received named pipe information from server
attempting to connect client to server...
client has connected to server
[Info  - 4:04:41 AM] [Program] Language server initialized

**SYSTEM INFORMATION AND A/B EXPERIMENT INFO**
Extension version: 2.1.11
VS Code version: Code 1.95.2 (e8653663e8840adaf45af01eab5c627a5af81807, 2024-11-07T11:07:22.054Z)
OS version: Windows_NT x64 10.0.22631
Modes:

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|11th Gen Intel(R) Core(TM) i5-1135G7 @ 2.40GHz (8 x 2419)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: enabled_on<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>skia_graphite: disabled_off<br>video_decode: enabled<br>video_encode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled<br>webgpu: enabled<br>webnn: disabled_off|
|Load (avg)|undefined|
|Memory (System)|7.80GB (1.88GB free)|
|Process Argv|--crash-reporter-id 79a453aa-78d8-4665-aed5-0af81c49eefd|
|Screen Reader|no|
|VM|0%|
</details><details>
<summary>A/B Experiments</summary>

```
vsliv368cf:30146710
vspor879:30202332
vspor708:30202333
vspor363:30204092
vscod805:30301674
binariesv615:30325510
vsaa593:30376534
py29gd2263:31024239
c4g48928:30535728
azure-dev_surveyone:30548225
962ge761:30959799
pythongtdpath:30769146
pythonnoceb:30805159
asynctok:30898717
pythonmypyd1:30879173
2e7ec940:31000449
pythontbext0:30879054
cppperfnew:31000557
dsvsc020:30976470
pythonait:31006305
dsvsc021:30996838
bdiig495:31013172
dvdeprecation:31068756
dwnewjupytercf:31046870
impr_priority:31102340
nativerepl1:31139838
refactort:31108082
pythonrstrctxt:31112756
cf971741:31144450
iacca1:31171482
notype1cf:31157160
5fd0e150:31155592
dwcopilot:31170013

```

</details>

**Comment by NonExisto** [comment]
Solved issue by installing vc++ redistr from [here](https://learn.microsoft.com/en-Us/cpp/windows/latest-supported-vc-redist?view=msvc-170). Both x64 and x86 are required for fresh windows installation
